- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/PreferredButtonResource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraViewController+Constraints.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/DocumentPickerCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/HelpMenuViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/No results/ImageAnalysisNoResultsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Open with tutorial/OpenWithTutorialViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Supported formats/SupportedFormatsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewMainCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewPagesCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/PageStateView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingContainerViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/HelpMenuViewControllerTests.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/PageStateViewTests.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/SupportedFormatsViewControllerTests.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/ZoomedImageView.swift
Fix Supported formats screen:
- Section header is under the navigation bar and is only partially visible.
- Icons are not positioned correctly. They are in the top left of their cell and are cut off. Tested on a device with iPhone 11 iOS 14.6 and on a simulator with iOS 15.
Remove check for iOS 11
Fixed iOS 11 deprications
> Pia 1948 review notes

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/PreferredButtonResource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Supported formats/SupportedFormatsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewMainCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewPagesCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/PageStateView.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/GiniCaptureTestsHelper.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/HelpMenuViewControllerTests.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/OpenWithTutorialViewControllerTests.swift
refactor(GiniCaptureSDK): Uses util method for Bundle -> giniCaptureBundle().
PIA-2076
> refactor(GiniCaptureSDK)

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Payments/PaymentService.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/PaymentServiceTests.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/PaymentTests.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/SessionManagerMock.swift
- Fixes GiniHealthAPILibrary: payment provider with id method.
- Fixed test for paymentService.
> Pia 2040 fix tests

- HealthSDK/GiniHealthSDK/Documentation/source/Integration.md
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewModel.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/Info.plist
- Moved the "Done" button on the Numpad to the right.
- Fixed "Available" typo.
- Example: add test scheme and interface file name in Info.plist.
> Pia 1776 done button position

- HealthSDK/GiniHealthSDK/.jazzy.yaml
- HealthSDK/GiniHealthSDK/Documentation/source/Event tracking guide.md
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/Tracking/GiniHealthTrackingDelegate.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/Tracking/TrackingEvent.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/ComponentAPICoordinator.swift
> Pia 2142 tracking docs

- CaptureSDK/GiniCaptureSDK/Documentation/source/Integration.md
Update integration guide:
* Add snippet for Screen API with custom networking.
> docs(GiniCaptureSDK): Add snippet for Screen API with custom networking

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBank.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
feat(GiniBankSDK): Add initializer for Screen API with custom networking support.
* Add method for setting the Gini Bank Configuration.
> Pia 2171 custom networking

- BankSDK/GiniBankSDK/Documentation/source/Integration.md
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBank.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
Update integration guide:
Add snippet for Screen API with custom networking.
> Pia 2172 custom networking screen api

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDKVersion.swift
- CaptureSDK/GiniCaptureSDKPinning/Package-release.swift
- CaptureSDK/GiniCaptureSDKPinning/Sources/GiniCaptureSDKPinningVersion.swift
chore(GiniCaptureSDK): Bumps version to 1.2.0
PIA-2146
> Release GiniCaptureSDK 1.2.0

- BankSDK/GiniBankSDK/Package-release.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDKVersion.swift
- BankSDK/GiniBankSDKPinning/Package-release.swift
- BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinningVersion.swift
> Release 1.2.0

- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthConfiguration.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/ComponentAPIDocumentsService.swift
- Adds `payButtonTitleFont` for the title font customization. 
- Health SDK Example updates.
> Pia 2355 pay button font

- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthConfiguration.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/ComponentAPIDocumentsService.swift
- Add a status bar style customization option for the payment review screen.
> Pia 2338 status bar style

- BankAPILibrary/GiniBankAPILibrary/Documentation/source/Getting started.md
Add links for the feedback guidelines and the feedback test case example.
PIA-1883
> docs(GiniBankAPILibrary)

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Base.lproj/Main.storyboard
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SelectAPIViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniCapture.swift
- Fix the Gini Capture SDK version.
> Pia 2366 version

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBank.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift
fix(GiniBankSDK): Add pragma for doc improvement.
PIA-2510
> Doc update

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DigitalInvoiceOnboarding.storyboard
> fix(GiniBankSDK): Fix background color customisation for the return assistant onboarding screen

- BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraButtonsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraViewController.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/AppCoordinator.swift
Allow camera customizations: 
-  camera container view background color,
-  camera preview frame color,
-  camera buttons view background color.
> Pia 2522 camera

- BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
- Document customization options for the `Help item` on the camera screen.
> Pia 2525 help button

- .github/workflows/health-api-library.check.yml
- GiniMobile.xcworkspace/contents.xcworkspacedata
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/GiniHealthAPI.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/SessionManager.swift
- HealthAPILibrary/GiniHealthAPILibraryPinning/Sources/GiniHealthAPILibraryPinning/GiniHealthAPI+Pinning.swift
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/AppDelegate.swift
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/Assets.xcassets/AccentColor.colorset/Contents.json
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/Assets.xcassets/AppIcon.appiconset/Contents.json
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/Assets.xcassets/Contents.json
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/Base.lproj/LaunchScreen.storyboard
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/Base.lproj/Main.storyboard
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/Info.plist
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/SceneDelegate.swift
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryExample/ViewController.swift
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExample.entitlements
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExample.xcodeproj/project.pbxproj
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExample.xcodeproj/xcshareddata/xcschemes/GiniHealthAPILibraryPinningExample.xcscheme
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExample.xcodeproj/xcshareddata/xcschemes/GiniHealthAPILibraryPinningExampleTests.xcscheme
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExampleTests/GiniHealthAPILibraryPinningIntegrationTests.swift
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExampleTests/GiniHealthAPILibraryTests.swift
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExampleTests/IntegrationTests.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample.xcodeproj/xcshareddata/xcschemes/GiniHealthSDKPinningExample.xcscheme
- Add `URLSessionDelegate` class for passing into the lib with pinning initializer.
- Add an example for GiniHealthAPILibraryPinning.
- Add integration tests for the public methods.
- Update check workflow.
> Pia 2537 pinning health

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingViewController.swift
- Fix content size for scrollView. The scroll view content was extending under the navigation bar.
> Pia 2626 onboarding fix

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingContainerViewController.swift
Page control dots count equals onboarding pages count.
PIA-2632
> fix(GiniCaptureSDK)

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
- remove 'X' label between quantity and price fields while editing the card
> Pia 2714 - remove 'X' label

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/GiniTextField.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Price.swift
- BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/String+UtilsTests.swift
- Limit amount textfield to only 2 digits after comma.
> Pia 2718 2 digits after comma

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/GiniTextField.swift
- enable pay button when total > 0
- change pay button title when non of the items selected
- don't hide addons price when non of the items selected
> Pia 2696 disabled pay button

- BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
Fix image name for Digital Invoice Info screen -> https://developer.gini.net/gini-mobile-ios/GiniBankSDK/customization-guide.html#info-screen
> docs(GiniBankSDK): fix image name for Digital Invoice Info screen

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/GiniTextField.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.stringsdict
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.stringsdict
- when the toggle will be deactivated the rest of the screen is turning grey
- fix unwanted behaviour when 0 quantity is pressed
> Pia 2754-0-qantity

- BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceStrings.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceTotalPriceCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/GiniTextField.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/de.lproj/LocalizableCustomName.strings
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/en.lproj/LocalizableCustomName.strings
- limit quantity to 99999
- add margin between total price and label
> Pia 2787 limit quantity

- BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
- Fix customization guide: other changes and disable…d titles for pay button.
> docs(GiniBankSDK): 

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
Remove "Save functionality" when the back button is clicked.
PIA-2810
> fix(GiniBankSDK):

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/GiniTextField.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
Disables the save button:
- when the price field was cleared;
- when the price is "0.00".
> Pia 2813 new article

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/GiniTextField.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
-  Allow setting a background color for separator view
> Pia 2847 vertical line

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIFont.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpFormatsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpMenu/HelpMenuDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpTipsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpFormatsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpImportViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpFormatSectionHeader.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpTipCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/AlbumsHeaderView.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/HelpScreen/HelpFormatSectionHeader.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/SupportedFormatsViewControllerTests.swift
- add support for new fonts styling according to new UI designs
> Pia 2853 help screen colors

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIFont.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpFormatsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpTipsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpImportViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpFormatCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpImportCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpTipCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
- add accessibility label for images
- fix dynamic sizing for bold textstyle
> Pia 2859 help accessibility

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Utils.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpFormatsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpImportViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpMenuViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpTipsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/HelpScreen/HelpFormatSectionHeader.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/HelpScreen/HelpImportCell.xib
- Fixed help screen margins on iPad
> Pia 3012 fix ipad margins

- .github/workflows/bank-sdk.publish.example.app.yml
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDKExample/Tests/ExtractionFeedbackIntegrationTest.swift
- CaptureSDK/GiniCaptureSDKPinningExample/Tests/ExtractionFeedbackIntegrationTest.swift
PIA-3069
add German translations for help screens
> feat(GiniCaptureSDK): add DE translations for help screens

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/de.lproj/LocalizableCustomName.strings
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/en.lproj/LocalizableCustomName.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpMenu/HelpMenuDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpMenu/HelpMenuItem.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> fix(GiniCaptureSDK): fix typos and errors in DE translation

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankUtils.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/GiniColors.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/GiniCaptureUtils.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/GiniColors.swift
Added colors to list
Remove optionality on preferred colors
> refactor Add new color constants, remove optionality of preferred colors

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceAddonCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceFooterCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceItemsCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceTotalPriceCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalLineItemTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/ReturnAssistantConfiguration.swift
- BankSDK/GiniBankSDKPinningExample/GiniBankSDKExample/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIColor.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraButtonsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/QRCodeDetectedPopupView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/AlbumsHeaderView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/ImagePickerViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/ImageAnalysisNoResultsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewPagesCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/OnboardingOld/OnboardingContainerViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/OnboardingOld/OnboardingPage.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/MultipageCollectionCellPresenterTests.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/MultipageReviewViewControllerTests.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/AppCoordinator.swift
Refactored GiniColors initializer
Removed the long initilizer
Added util function to return UIColor for cleaner code
Remove UIColor extension which did the same as the new function, but less readable
> Refactor ginicolor initializer

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsViewContainer.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/CaptureSuggestionsViewContainer.xib
feat(GiniCaptureSDK) Add accesibility requirments for image, title and description
> Accessibility requirements on the analysis screen

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/ReturnAssistantConfiguration.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/UIFont+Utils.swift
Added custom text styles to BankSDK
> fix(GiniBankSDK) Fix customization of fonts

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> Pia 2938 update german strings

- BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/de.lproj/InfoPlist.strings
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/en.lproj/InfoPlist.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
> fix(GiniCaptureSDK) Fix overlay constraints to fill the entire screen

- .github/workflows/bank-sdk.publish.example.app.yml
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Base.lproj/Main.storyboard
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/ResultTableViewController.swift
- BankSDK/GiniBankSDKPinningExample/GiniBankSDKExample/Base.lproj/Main.storyboard
- BankSDK/GiniBankSDKPinningExample/GiniBankSDKExample/ResultTableViewController.swift
change system type cell into custom cell in example apps. It seems it causes layout problems in executable version
> Pia 3163 update xcode

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
- BankSDK/GiniBankSDKExample/Tests/ScreenAPICoordinator+UI_Only.swift
- BankSDK/GiniBankSDKPinningExample/GiniBankSDKExample/AppCoordinator.swift
- BankSDK/GiniBankSDKPinningExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
- BankSDK/GiniBankSDKPinningExample/Tests/ScreenAPICoordinator+UI_Only.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/ContainerNavigationController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/GiniBarButtonItem.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UINavigationController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ScreenAPICoordinator.swift
- CaptureSDK/GiniCaptureSDKPinningExample/Example Swift/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDKPinningExample/Example Swift/AppDelegate.swift
- CaptureSDK/GiniCaptureSDKPinningExample/Example Swift/ScreenAPICoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- Extends configuration with `customNavigationController`
- Remove granular customization for the navigation bar
- Add custom implementation into example apps
- Update default navigation bar appearance
- Fix tests
> Pia 2863 top navigation

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> fix(GiniCaptureSDK): Add padding on the margins for analysis screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
> PIA-3201: fix(GiniCaptureSDK): fix navigation of back button for  help screens

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
- camera orientation fixed on iPad
PIA-3204
> fix(GiniCaptureSDK): fix camera preview orientation issue

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
> PIA-3218: fix(GiniCaptureSDK): fix back button on camera screen when bottom navigation bar enabled

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Analysis.swift
> feature(GiniCaptureSDK): Top navigation on analysis screen

- CaptureSDK/GiniCaptureSDKExample/Example Swift/Base.lproj/Main.storyboard
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ResultTableViewController.swift
- Fixed result screen layout
- Hide component API button
PIA-3275
> chore(GiniCaptureSDKExample): 

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/CustomLoadingIndicator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CustomLoadingIndicatorAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/QRCodeOverlay.swift
Renamed the custom loading indicator adapter as described in [PIA-3290](https://ginis.atlassian.net/jira/software/c/projects/PIA/boards/53?modal=detail&selectedIssue=PIA-3290&assignee=62f28ce248e310e672977ab4)
> Pia 3290 rename analysis screen loading indicator adapter to custom loading indicator adapter

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/DefaultReviewBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewScreenBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/ReviewScreen/ReviewBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
Without and with bottom navigation
> Pia 3307 Shorten button titles and group them in the middle

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/BackButtonBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/Views/OnboardingBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/Camera/CameraBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/OnboardingScreen/OnboardingBottomNavigationBar.xib
> feature(GiniCaptureSDK): Add light mode colors for bottom navigation

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
Fix issues: 
• Shown page is not highlighted when returning from the camera without taking a picture
• 1st page: no issues
2nd page: blue frame disappears and reappears for active page 
3rd page: blue frame disappears and reappears for active page and appears also for neighbouring page
4th and 5th page: blue frame disappears and reappears for active page
> fix(GiniCaptureSDK): Fix cell selection

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> Pia 3305 rename english text upload pdf to upload files

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewCollectionCell.swift
> fix(GiniCaptureSDK): Change color on imageview

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewZoomViewController.swift
> feature(GiniCaptureSDK): Update reference documentation

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
> fix(GiniCaptureSDK): Fix layout on QR code only with bottom navigation

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
[This should not happen](https://ginis.atlassian.net/jira/software/c/projects/PIA/boards/53?modal=detail&selectedIssue=PIA-3298&assignee=62f28ce248e310e672977ab4)
> fix(GiniCaptureSDK): Remove focus rectangle for subject area change

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
Analysis screen reference documentation
> Pia 2945 update reference documentation for analysis screen

- BankSDK/GiniBankSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Integration.md
- Update the Integration guide for the Help screen.
> Pia 2856 integration help

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Base.lproj/Main.storyboard
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/ResultTableViewController.swift
> chore(GiniBankSDKExample): Fixed result screen layout

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/BottomButtonsViewModel.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Analysis.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/DocumentService.swift
PIA-3454
[PIA-3454]: https://ginis.atlassian.net/browse/PIA-3454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(GiniCaptureSDK): trigger error screen on upload failure

- CaptureSDK/GiniCaptureSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Migration to version 3.x.x.md
- Add migration for Onboarding screens
- Add migration for Help screens
> Pia 2955 helpscreen migration

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
Navigation is already fixed, in this PR I fixed the button layout if multipage is disabled
> fix(GiniCaptureSDK): Fix button allignment on review screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
Change wording for "Enter manually" in german
> fix(GiniCaptureSDK): Fix German localization

- BankSDK/GiniBankSDK/Documentation/source/Features.md
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Migration to version 3.x.x.md
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingPage.swift
> feature(GiniCaptureSDK): Onboarding page documentation

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpMenu/HelpMenuDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpMenu/HelpMenuItem.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpRoundedCornersDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpTipsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Protocols/HelpBottomBarEnabledViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Protocols/HelpCellProtocol.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpFormatsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpImportViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpMenuViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpTipsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/ImageAnalysisNoResultsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpFormatCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpImportCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpMenuCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpTipCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
> feature(GiniCaptureSDK): Add documentation for help screen 

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpFormatsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
> fix(GiniCaptureSDK): Fix header scrolling on No results screen

- CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Features.md
- Add review screen customization options
> docs(GiniCaptureSDK): Add review screen customisation options

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/HelpBottomNavigationBar/CustomBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/DefaultImagePickerBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/ImagePickerBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/ImagePickerViewController.swift
Screenshots from iPhone 13 pro, iOS 15 and iPhone SE iOS 12.4
> Pia 3490 i os bottom nav missing on image picker

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
> fix(GiniCaptureSDK): Fix width for caption suggestion

- CaptureSDK/GiniCaptureSDK/Documentation/source/Migration to version 3.x.x.md
- Add migration section for the review screen PIA-2933
> docs(GiniCaptureSDK): Add migration guide

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/Camera/CameraiPad.xib
> fix(GiniCaptureSDK): Fix constraints

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
> fix(GiniCaptureSDK): Fix cell status activation

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/GiniImages.xcassets/delete_icon.imageset/delete_icon.pdf
> feature(GiniCaptureSDK): Change delete icon

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
> fix(GiniCaptureSDK): Fix constraints breaking on review screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniError.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpImportViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> fix(GiniCaptureSDK): Add accessibility description for images

- CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Migration to version 3.x.x.md
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/GiniNetworkingScreenAPICoordinator.swift
- Add customization options, features, and migration for the error screen.
PIA-3330, PIA-3335, PIA-3332
> docs(GiniCaptureSDK):

- CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Migration to version 3.x.x.md
- Add customization options for no result screen
PIA-2953
> docs(GiniCaptureSDK): Add customization options for no result screen

- BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/HelpBottomNavigationBar/CustomBottomNavigationBarAdapter.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/ReviewBottomNavigationBar/CustomReviewScreenBottomNavigationBar.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/ReviewBottomNavigationBar/CustomReviewScreenBottomNavigationBar.xib
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/ReviewBottomNavigationBar/CustomReviewScreenBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/CameraBottomNavigationBar/CustomCameraBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/CameraBottomNavigationBar/CustomCameraBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDKExample/Example Swift/CameraBottomNavigationBar/CustomCameraBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/HelpBottomNavigationBar/CustomBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/HelpBottomNavigationBar/CustomBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDKExample/Example Swift/HelpBottomNavigationBar/CustomBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/OnboardingBottomNavigationBar/CustomOnboardingBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/OnboardingBottomNavigationBar/CustomOnboardingBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDKExample/Example Swift/OnboardingBottomNavigationBar/CustomOnboardingBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ReviewBottomNavigationBar/CustomReviewScreenBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ReviewBottomNavigationBar/CustomReviewScreenBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ReviewBottomNavigationBar/CustomReviewScreenBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/UIView.swift
- CaptureSDK/GiniCaptureSDKExample/GiniCaptureSDKExample.xcodeproj/project.pbxproj
Check that the files belong to the correct target.
> Pia 3655 the bottom navigation example implementation is missing

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/BottomLabelButton.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/ReviewScreen/ReviewBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> feature(GiniCaptureSDK): Add content view and scrollview for big fonts

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/Camera/CameraBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/Camera/CameraPhone.xib
> fix(GiniCaptureSDK):  Fix camera bottom navigation

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/BottomLabelButton.swift
> fix(GiniCaptureSDK): Fix button alignment

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController+Popups.swift
Changed tintColor for import bottom sheet
> fix(GiniCaptureSDK): Add tintcolor for bottomsheet

- BankAPILibrary/GiniBankAPILibraryExample/GiniBankAPILibraryExampleTests/ExtractionFeedbackIntegrationTest.swift
- BankAPILibrary/GiniBankAPILibraryPinningExample/GiniBankAPILibraryPinningExampleTests/ExtractionFeedbackIntegrationTest.swift
- BankSDK/GiniBankSDKExample/Tests/ExtractionFeedbackIntegrationTest.swift
- BankSDK/GiniBankSDKPinningExample/Tests/ExtractionFeedbackIntegrationTest.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/AlbumsFooterView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/AlbumsHeaderView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/AlbumsPickerTableViewCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/AlbumsPickerViewController.swift
- CaptureSDK/GiniCaptureSDKExample/Tests/AlbumsPickerViewControllerTests.swift
- CaptureSDK/GiniCaptureSDKExample/Tests/ExtractionFeedbackIntegrationTest.swift
- CaptureSDK/GiniCaptureSDKPinningExample/Tests/AlbumsPickerViewControllerTests.swift
- CaptureSDK/GiniCaptureSDKPinningExample/Tests/ExtractionFeedbackIntegrationTest.swift
> Album picker accessibility

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpTipsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpTipsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> fix(GiniCaptureSDK): Fix header missing

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Info.plist
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorType.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> fix(GiniCaptureSDK): Fix error icons

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
> fix(GiniCaptureSDK): Hide help button on QR code only mode

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
> fix(GiniCaptureSDK): Expand crop area

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DigitalInvoiceOnboarding.storyboard
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/MultilineTitleButton.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/Views/OnboardingImageView.swift
In order to test it, when building, uncomment line 96 from Appcoordinator.swift on GiniBankSDKExample
> Pia 3581 allow injecting an image container view

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
> Small fixes and improvements for customization

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpImportViewController.swift
> fix(GiniCaptureSDK): Fix bottom padding on help screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
> fix(GiniCaptureSDK): Turn frame with orientation change

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceTableViewHeader.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceAddOnListCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceViewController.swift
> feature(GiniBankSDK): Remove unused public methods, add reuseidentifiers

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/NameLabelView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/PriceLabelView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/QuantityView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DigitalLineItemTableViewCell.xib
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
> Pia 3601 fulfill accessibility requirements

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DefaultDigitalInvoiceOverviewNavigationBarBottomAdapter.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceBottomNavigationBar.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Help/DefaultBackButtonBottomNavigationBar.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Help/DefaultDigitalInvoiceHelpNavigationBarBottomAdapter.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DefaultBackButtonBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/BackButtonBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/GiniBarButton.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/DefaultCameraBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/DefaultImagePickerBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/DefaultHelpBottomNavigationBarAdapter.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/BackButtonBottomNavigationBar.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/Camera/CameraBottomNavigationBar.xib
Navigation buttons on the bottom navigation bar should not scale.
> Pia 3889 update the bottom navigation bar buttons

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Base.lproj/Main.storyboard
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/ResultTableViewCell.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/ResultTableViewController.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/Base.lproj/Main.storyboard
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ResultTableViewCell.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ResultTableViewController.swift
- CaptureSDK/GiniCaptureSDKExample/Example Swift/ScreenAPICoordinator.swift
- CaptureSDK/GiniCaptureSDKExample/GiniCaptureSDKExample.xcodeproj/project.pbxproj
This contains the other (Bank SDK example) changes also
> Pia 3856 capture extractions edit

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/GiniBarButton.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewBottomNavigationBar.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
Fix voice over for these tickets:
https://ginis.atlassian.net/browse/PIA-3913
https://ginis.atlassian.net/browse/PIA-3915
https://ginis.atlassian.net/browse/PIA-3916
https://ginis.atlassian.net/browse/PIA-3919
https://ginis.atlassian.net/browse/PIA-3920
> Pia 3913 release candidate ios voice doesnt pronounce button if select cancel

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/String.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/QRCodesExtractor.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniQRCodeDocument.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/GiniQRCodeDocumentTests.swift
> fix(GiniCaptureSDK): Change new line splitting function.

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/String.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/QRCodesExtractor.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniQRCodeDocument.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/GiniQRCodeDocumentTests.swift
> Pia 3356 qr code validation on client failed 

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/NameLabelView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/PriceLabelView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/QuantityView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
> feature(GiniBankSDK): Add error labels

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
> fix(GiniCaptureSDK): Fix camera preview on simulator

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
> fix(GiniBankSDK): Fix rotation layout update

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
> Pia 3966 fix crash

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemViewController.swift
Fix animation when keyboard is presented.
> Hide keyboard when tapping outside of edit container - QA

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
> fix(GiniCaptureSDK): Fix aspect ratio of camera preview - QA

- BankSDK/GiniBankSDK/Documentation/source/Integration.md
- BankSDK/GiniBankSDK/Documentation/source/Migration to version 3.x.x.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Integration.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Migration to version 3.x.x.md
* Updates feedback sending info in integration guides.
* Updates steps on how to launch the Capture SDK in integration guide.
* Adds steps on how to launch the Bank SDK to integration guide.
* Add section for feedback sending to migration guides.#
* Other minor improvements.
> Pia 3967 update feedback docs

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/IconHeader.xib
Centre the header for the no results and error screen
PIA-3945
> chore(GiniCaptureSDK): Centre the header for the no results and error screen

- BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
- BankSDK/GiniBankSDK/Documentation/source/Event tracking guide.md
- BankSDK/GiniBankSDK/Documentation/source/Features.md
- BankSDK/GiniBankSDK/Documentation/source/Integration.md
- BankSDK/GiniBankSDK/Documentation/source/Migration to version 3.x.x.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Event tracking guide.md
- Add general RA feature description
- Customization for the Digital Invoice Edit Article screen
- Update event tracking guides
> Pia 3599 docs

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/GiniCaptureUtils.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/DocumentPickerCoordinator.swift
> fix(GiniCaptureSDK): Remove deprecated function - QA

- BankSDK/GiniBankSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Features.md
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
- Hide camera picker
- Remove camera picker mentions from the docs
> Pia 3972 hide camera lens switcher

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Utils.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpFormatsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpRoundedCornersDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpTipsDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpMenuViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpTipsViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Views/HelpTipCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/HelpScreen/HelpFormatSectionHeader.xib
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/HelpScreen/HelpTipCell.xib
Please check also the help screen when testing because it uses the same UI. 🙏 
PIA-3969
> fix(GiniCaptureSDK): Fix layout issues on no results and help screen

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemView.swift
> fix(GiniBankSDK): Fix error label sizes

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIFont.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraNotAuthorizedView.swift
Fix access screen accessibility, this is how it looks on iPhone 12 mini.
> fix(GiniCaptureSDK): Fix accessibility for no access screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
> fix(GiniCaptureSDK): Fix crash when delegate is nil

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/QRCodeOverlay.swift
> fix(GiniCaptureSDK): Fix QR code overlay big fonts

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
> fix(GiniCaptureSDK): Fix cancel button function

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/IconHeader.xib
> fix(GiniCaptureSDK): Limit the header text up to 5 lines.

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Bottom navigation/DigitalInvoiceBottomNavigationBar.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceAddOnListView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DigitalLineItemTableViewCell.xib
> Pia 3962 release candidate i os incorrect displaying of values if in german version enlarge mode is on

- BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
- BankSDK/GiniBankSDK/Documentation/source/Migration to version 3.x.x.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Migration to version 3.x.x.md
- Updated customization guide with 3.1.0 Figma links.
- Remove the direct figma links from Migration 3.X.X -> used links on the customization guide
> Pia 4017 no results figma

- BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/CustomOnboardingIllustrationAdapter.swift
- GiniMobile.xcworkspace/xcshareddata/swiftpm/Package.resolved
update Lottie dependency to the latest version
PIA-4084
> chore(GiniBankSDK): changed from upToNextMajorVersion to exactVersion to better control the updates of dependencies

- BankAPILibrary/GiniBankAPILibrary/Documentation/source/Getting started.md
- BankSDK/GiniBankSDK/Documentation/source/Integration.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/Integration.md
> Pia 3989 update customer documentation

- BankSDK/GiniBankSDK/Documentation/source/Open with guide.md
- BankSDK/GiniBankSDKExample/GiniBankSDKShareExtension/ShareViewController.swift
- Remove copy/paste comment.
- Add Open with guide from Photos app.
PS I've used the links on the snippets for `main` branch so they will not work in this PR.
They can be checked if you replace "main" ->"PIA-3186_share_extension".
> Pia 3187 share extension docs

- BankSDK/GiniBankSDK/Documentation/source/QR Code scanning guide.md
- CaptureSDK/GiniCaptureSDK/Documentation/source/QR Code scanning guide.md
- Update the QR code scanning guide
> Pia 3472 qr code docs

- .github/workflows/bank-sdk.publish.example.app.yml
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Credentials.plist
- We used checkout step 2 time
> Fix missing credentials in the publish workflow

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/Views/IconHeader.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/IconHeader.xib
- Fix the layout on iPhone for error/ no result header
- Update text alignment and padding on iPad
- Refactor configuration of the constraints into view-related methods
> Pia 4016 fix header layout for error and  no result screens

- BankSDK/GiniBankSDK/Pod/README.md
- BankSDK/GiniBankSDKPinning/Pod/README.md
Add info on how to create XCFramework zips which work with Cocoapods.
> Update cocoapods release readme

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController+CellType.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController+SegmentedOptionModel.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController.swift
- BankSDK/GiniBankSDKExample/Tests/SettingsViewControllerTests.swift
- Add an entry point option to the settings screen, and tests.
> PIA-4292_entrypoint_example

- .github/workflows/bank-sdk.build.xcframeworks.yml
- Add build phase script to sign generated XCFrameworks
- Cleanup the command that creates the XCFrameworks
> Pia 4305 v1 sign xc frameworks

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/PrivacyInfo.xcprivacy
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/PrivacyInfo.xcprivacy
- Add PrivacyInfo manifest file to GiniHealthSDK
- Add PrivacyInfo manifest file to GiniHealthAPILibrary
> Pia 4438 v1 add privacy manifest gini health api libray and gini health sdk

- .github/workflows/bank-sdk.build.xcframeworks.yml
- Add build phase script to sign generated XCFrameworks
- Cleanup the command that creates the XCFrameworks
> Pia 4305 v3 sign xc frameworks

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/PrivacyInfo.xcprivacy
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/PrivacyInfo.xcprivacy
- Add `PrivacyInfo` manifest file to GiniHealthSDK
- Add `PrivacyInfo` manifest file to GiniHealthAPILibrary
> Pia 4438 v3 add privacy manifest gini health api libray and gini health sdk

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Analysis.swift
> fix(GiniCaptureSDK): Fix retry event tracking on the Error screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
Fix spelling mistakes:
- QR code/ PDF Document - German/English version
- correct usage of the formal form in Deutsch
- Photo/Foto - English/German version
- correct some messages to be more grammatically correct
PIA-4387
> fix(GiniCaptureSDK): Fix some spelling mistakes in the new UI/UX SDK iOS

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/IBAN/IBANKnowledge.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/IBAN/IBANRecogniser.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/IBANRecogniserTests.swift
Fixes regex for the universal ibans, adds a test 
Fix indentation
PIA-4628
> fix(GiniCaptureSDK): Fixes regex for the universal ibans, adds a test

- BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/CameraMock.swift
- BankSDK/GiniBankSDKPinning/Tests/GiniBankSDKPinningTests/CameraMock.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/GiniCaptureUtils.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController+Crop.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraPreviewView.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/CameraMock.swift
- display detected IBANs that are fully inside the frame
PIA-4618
> feat(GiniCaptureSDK): Limit IBAN detection to the camera frame

- Gemfile.lock
- GiniMobile.xcworkspace/xcshareddata/IDETemplateMacros.plist
- added a template with a custom header comment license for all the new files that will be created
- Gemfile automatic updates
> Add custom copyright and remove created by for new files

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/DemoViewController.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/Info.plist
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/AVCaptureVideoOrientation.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIImage.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIWindow.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/DeviceOrientation.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/Views/OnboardingPageCell.swift
- fixes the device orientation and text orientation for `VNImageRequestHandler`
- fixes camera frame view after rotating the device to the right(landscape) and back, to the left, to portrait
- fixes IBAN detection Upside down
- isolates the usage of `UIApplication.shared.statusBarOrientation` because starting with iOS 13.0 will be deprecated
PIA-4627
> PIA 4627 Detecting IBAN on the iPad landscape and upside down

- BankSDK/GiniBankSDKExample/Tests/TransferSummaryIntegrationTest.swift
Reenable test for RA `LineItems`
> fix(GiniBankSDK): Enable the`LineItems` unit tests

- .github/workflows/health-sdk.publish.example.apps.yml
- fastlane/Fastfile
Added workflow for publishing Gini Health SDK Example
> Publish health example

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/Auth/SessionManager+Auth.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/GiniError.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/KeyStore.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/SessionManager.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/ScreenAPICoordinator.swift
- Fixes anonymous user to log in again after each GiniHealthApiLibrary launch
- cleanup code
BSDK-26
> Bsdk 26 anonymous user not logged in again after each ios gini health api library launch

- .github/workflows/health-sdk.publish.example.apps.yml
- ExportOptionsHealthExample.plist
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExampleTests/GiniHealthAPILibraryPinningIntegrationWrongCertificatesTests.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/GiniHealthSDKExample.entitlements
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKPinningExampleTests/GiniHealthSDKPinningExampleWrongCertificatesTests.swift
fix(GiniHealthAPILibraryPinning): Fixes error type with a wrong pinning certificate
> fix(GiniHealthAPILibraryPinning): Fixes error type with a wrong pinning certificate

- BankAPILibrary/GiniBankAPILibrary/Documentation/source/Installation.md
- BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/GiniBankAPILibraryVersion.swift
- BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/DocumentServiceTests.swift
- BankAPILibrary/GiniBankAPILibraryPinning/Package-release.swift
- BankAPILibrary/GiniBankAPILibraryPinning/Sources/GiniBankAPILibraryPinning/GiniBankAPILibraryPinningVersion.swift
- BankSDK/GiniBankSDK/Package-release.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/GiniBankSDKVersion.swift
- BankSDK/GiniBankSDKPinning/Package-release.swift
- BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinning/GiniBankSDKPinningVersion.swift
- CaptureSDK/GiniCaptureSDK/Package-release.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/GiniCaptureSDKVersion.swift
- CaptureSDK/GiniCaptureSDKPinning/Package-release.swift
- CaptureSDK/GiniCaptureSDKPinning/Sources/GiniCaptureSDKPinning/GiniCaptureSDKPinningVersion.swift
Release candidate for https://ginis.atlassian.net/browse/PP-290
PP-290
> Bank release candidate v 3.7.3

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- configuration message updated 
PP-333
> feat(GiniBankSDK): Disable the return reasons feature by default

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
- both english and german
PP-336
> feat(GiniBankSDK): Edit text for the third help item in Digital invoice onboarding screen

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/GiniBankSDKVersion.swift
- BankSDK/GiniBankSDKPinning/Package-release.swift
- BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinning/GiniBankSDKPinningVersion.swift
> feat(GiniBankSDK):  Bumps version 3.7.4

- HealthAPILibrary/GiniHealthAPILibrary/Documentation/sections/Documentation.md
- HealthAPILibrary/GiniHealthAPILibrary/Package.swift
- HealthAPILibrary/GiniHealthAPILibrary/README.md
- HealthAPILibrary/GiniHealthAPILibraryPinning/Package.swift
- HealthSDK/GiniHealthSDK/Documentation/sections/Documentation.md
- HealthSDK/GiniHealthSDK/Package-release.swift
- HealthSDK/GiniHealthSDK/Package.swift
- HealthSDK/GiniHealthSDK/README.md
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponent/PaymentComponentsController.swift
- HealthSDK/GiniHealthSDKPinning/Package-release.swift
- HealthSDK/GiniHealthSDKPinning/Package.swift
Note: I didn't touch our code for minimising the 🐛 risk
> iOS 12 target insurance

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
Fix font style for the description label on the RA Onboarding screen
Figma to check: https://www.figma.com/file/mikn8kCBGSIil4DhDg7NNL/iOS-Gini-Bank-SDK-3.8-UI-Customisation?type=design&node-id=0%3A1&mode=design&t=6RBSLUCqtJ3nLUS1-1
PP-468
>  Fix font style for the description label on the RA Onboarding screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/AnalyticsProperties.swift
Fix the analytics value for the `screen` property event
PP-507
> fix(GiniCaptureSDK): Fix the analytics value for the `screen` property event

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Protocols/HelpBottomBarEnabledViewController.swift
Add missing event for help screen custom bottom bar
PP-393
> fix(GiniCaptureSDK): add help screen close event for custom bottom bar

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
Add missing event to custom bottom bar
> fix(GiniCaptureSDK): add camera back button event for custom bottom bar

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
Add missing events for review screen custom bottom bar
PP-389
> fix(GiniCaptureSDK): add processTapped & addPagesTapped events

- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/Extensions/UIView+Utils.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
> refactor(GiniHealthSDK): Remove the availability checks for iOS 11 (min target was raised to 12)

- CaptureSDK/GiniCaptureSDK/Package-release.swift
- CaptureSDK/GiniCaptureSDK/Package.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/AnalyticsManager.swift
- GiniMobile.xcworkspace/xcshareddata/swiftpm/Package.resolved
Add the Amplitude package to send same events that we sent in Mixpanel in order to analize which tool is the best.
> Integrate amplitude

- HealthSDK/GiniHealthSDK/Documentation/source/Customization guide.md
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Documentation/source/Integration.md
-  Update Figma links
-  Add how to change the height for a payment component
-  Mention to call a completion block for AlternativeTokenSource in a specific thread
https://ginis.atlassian.net/browse/IPC-264
https://ginis.atlassian.net/browse/IPC-80
> Doc update 4.1

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/AnalyticsManager.swift
> fix(GiniBankSDK): Remove duplicate `sdk_closed` event sent when tapping `Proceed` button in RA screen

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingViewController.swift
- Onboarding: "Get Started" button name instead of "Next"
PP-551
> fix(GiniCaptureSDK): Fix button title  in Onboarding screens

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/AnalyticsManager.swift
> PP-539 Add all event to the queue

- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample.xcodeproj/project.pbxproj
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample.xcodeproj/xcshareddata/xcschemes/GiniHealthSDKExample.xcscheme
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/CredentialsManager.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExampleTests/FileLoader.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExampleTests/GiniSetupHelper.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExampleTests/UploadDocumentsTests.swift
- Add test for importing files > 10 Mb
> feat(GiniHealthSDKExample): Add upload big files tests + retrieve extractions

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Model/Price.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/BottomNavigation/SkontoNavigationBarBottomAdapter.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewModel.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAmountView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAppliedAmountView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAppliedDateView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAppliedHeaderView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAppliedInfoView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoNotAppliedAmountView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoNotAppliedView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoProceedView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/GiniColors.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
> Pp 568 as a end user when i see skonto details i want to have an option to apply now skonto or reject skonto and pay in full

- .github/workflows/merchant-sdk.check.yml
- MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample.xcodeproj/project.pbxproj
- MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample.xcodeproj/xcshareddata/xcschemes/GiniMerchantSDKPinningExampleTests.xcscheme
EC-63
- Update Xcode for the check workflow
- Add params to the pinning example scheme
> fix(GiniMerchantSDK): Update Xcode for check workflow

- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/Extensions/UITableView+ReusableView.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/BankSelectionTableViewCell.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/BanksBottomView.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentInfoAnswerTableViewCell.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentInfoViewController.swift
Add ReusableView for handling reuseID, funcs for tableView to easy work with cells
> ref(MerchantSDK): refactor reusable views

- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/Extensions/GiniMerchantColors.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniColor.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchantConfiguration.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchantUtils.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/BankSelectionTableViewCellModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/BanksBottomViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/BottomSheetViewController.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/InstallAppBottomViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/MoreInformationViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentComponentViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentInfoAnswerTableViewCell.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentInfoBankCollectionViewCell.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentInfoQuestionHeaderViewCell.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentInfoViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PoweredByGiniViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/ShareInvoiceBottomViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/ShareInvoiceSingleAppView.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentReviewViewController.swift
Refactoring for colors in gini merchant
> ref(MerchantSDK): Add enum for colors

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/ExtractionResult.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Integration.md
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponent/PaymentComponentsController.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/GiniHealthTests.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/MockHelpers/MockPaymentComponents.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/PaymentComponentsControllerTests.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/Resources/extractionResultWithIBAN.json
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/Resources/extractionResultWithoutIBAN.json
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/InvoicesList/InvoicesListViewModel.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/ScreenAPICoordinator.swift
https://ginis.atlassian.net/browse/IPC-296
IPC-296
+ fix tests
> feat(GiniHealthSDK): Use payment_state instead of checkIfDocumentIsPayable

- BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
Add PhotosUI framework to fix crash with limited photos access 
PP-510 
PP-519
Need to check and update documentation
reproducable only on device. use steps in PP-519
> fix(GiniBankSDKExample): Add PhotosUI framework

- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/en.lproj/Localizable.strings
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Resources/en.lproj/Localizable.strings
> fix(GiniHealthSDK): Fix langs to install bottom sheet

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAppliedDateView.swift
> feat(GiniBankSDK): set initial picker date

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/Amplitude/AmplitudeBaseEvent.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/Amplitude/AmplitudeEventOptions.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/GiniAnalyticsManager.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/GiniAnalyticsUserProperty.swift
We decide to not set anymore the app_version and add bank_sdk_version and capture_sdk_version as user properties.
> Pp 646 add bank sdk version and capture sdk version as user properties

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController+SwitchOptionModel.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController.swift
- BankSDK/GiniBankSDKExample/Tests/SettingsViewControllerTests.swift
> PP-672 add skontoEnabled toggle to settings & update tests

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/APIResource.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/Client.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/GiniHealthAPI.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/DefaultDocumentService.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/DocumentService.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Payments/PaymentService.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/APIResourceTests.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/DocumentServiceTests.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/PaymentServiceTests.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/PaymentTests.swift
- HealthAPILibrary/GiniHealthAPILibraryExample/GiniHealthAPILibraryExampleTests/GiniHealthAPILibraryTests.swift
- HealthAPILibrary/GiniHealthAPILibraryPinning/Sources/GiniHealthAPILibraryPinning/GiniHealthAPI+Pinning.swift
- HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExampleTests/GiniHealthAPILibraryTests.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/GiniHealthTests.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/PaymentComponentsControllerTests.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/GiniMerchantSDKTests.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/PaymentComponentsControllerTests.swift
EC-69 Add API version parametr, update tests, update GiniHealthSDK, GiniMerchantSDK
> feat (GiniHealthAPILibrary): Add API version parametr

- BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/CameraMock.swift
- BankSDK/GiniBankSDKPinning/Tests/GiniBankSDKPinningTests/CameraMock.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController+Actions.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/CameraMock.swift
Prevent reinitializing camera every time it gets opened until it gets deallocated
> PP-523 fix camera issue when going back from help screen

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Help/BottomNavigation/DefaultSkontoHelpNavigationBottomBar.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Help/Views/SkontoHelpItemView.swift
> fix(GiniBankSDK): fix font size for help item

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/APIResource.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/ContentType.swift
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/GiniHealthAPI.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/InvoicesList/InvoiceTableViewCell.xib
- MerchantSDK/GiniMerchantSDK/Documentation/source/Testing.md
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/Adapter/DocumentService.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/GiniMerchantSDKTests.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/PaymentComponentsControllerTests.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/Resources/notSortedBanks.json
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/Resources/providers.json
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/Resources/sortedBanks.json
https://ginis.atlassian.net/browse/EC-110
> feat(GiniMerchantSDK): Switch to https://merchant-api.gini.net v1 IPC-110

- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/Extensions/NotificationsName.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/BanksBottomView.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/BanksBottomViewModel.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentComponentsController.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponent/PaymentInfoViewController.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Resources/de.lproj/Localizable.strings
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Resources/en.lproj/Localizable.strings
- MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/OrderDetailViewController.swift
https://ginis.atlassian.net/browse/EC-106
> feat(GiniMerchantSDK): Payment component should stay open EC-106

- MerchantSDK/GiniMerchantSDK/Documentation/source/Installation.md
- MerchantSDK/GiniMerchantSDK/Documentation/source/Integration.md
> feat(GiniMerchantSDK): Update integration guide 

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
I disabled help button while qrcode data is being processed
> PP-525 Help screen display Issue while scanning a QR code

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/DocumentPages/DocumentPagesViewController.swift
> fix(GiniBankSDK): Fix image overlap when uploading screenshots between document pictures

- HealthAPILibrary/GiniHealthAPILibrary/Documentation/source/Installation.md
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift
- HealthAPILibrary/GiniHealthAPILibraryPinning/Package-release.swift
- HealthAPILibrary/GiniHealthAPILibraryPinning/Sources/GiniHealthAPILibraryPinning/GiniHealthAPILibraryPinningVersion.swift
> feat(GiniHealthAPILibrary): Bumps version 4.3.0

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewModel.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
> fix(GiniBankSDK): fix pay by cash today edgecase

- .github/workflows/utilites.check.yml
- .github/workflows/utilites.release.yml
- GiniComponents/GiniUtilites/Sources/GiniUtilites/GiniUtilitesVersion.swift
- MerchantSDK/GiniMerchantSDK/Package-release.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/GiniMerchantSDKVersion.swift
-  Add workflows for Gini Utilities
-  Update version for Gini Merchant SDK
> Ec 129 rc merchant 1 0 0

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/TransactionDocs/Components/TransactionDocsItemView.swift
> fix(GiniBankSDK): Fix TD view paddings

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankUtils.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Bottom navigation/DigitalInvoiceBottomNavigationBar.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceProceedView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/QuantityView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Help/SkontoHelpViewModel.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoAlertFactory.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewModel.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/GiniBarButton.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIImage.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/GiniCaptureUtils.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniCaptureDocument.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/DocumentPickerCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Analysis.swift
Removed code duplications, extracted long properties into the intermediate constants, deleted empty lines/spaces, added type alias, shortened code comments
PS please review by comments
> Lint issues capture and bank

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/DocumentPages/Error/DocumentPagesErrorView.swift
> fix(GiniBankSDK): fix error view top padding

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/TransactionDocs/Models/TransactionDocsDocumentPagesViewModel.swift
> fix(GiniBankSDK): fix preview bottom info empty/nil items

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
> fix(GiniBankSDK): fix alert for no results

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/ExtractionResult.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/GiniHealthTests.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/MockHelpers/MockSessionManager.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/Resources/document5.json
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/Resources/test_doctorsname.json
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/InvoicesList/InvoiceTableViewCellModel.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/InvoicesList/InvoicesListViewModel.swift
> feat(GiniHealthSDK): Expose doctor's name 

- GiniComponents/GiniUtilites/Sources/GiniUtilites/URLOpener.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController+PaymentReviewViewModelDelegate.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/URLOpener.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/MockHelpers/MockUIApplication.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/GiniMerchantSDKTests.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/MockHelpers/MockUIApplication.swift
> fix(GiniHealthSDKExample): Fix To the banking app button should be disabled

- GiniComponents/GiniUtilites/Sources/GiniUtilites/URLOpener.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController+PaymentReviewViewModelDelegate.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/URLOpener.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/MockHelpers/MockUIApplication.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/GiniMerchantSDKTests.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/MockHelpers/MockUIApplication.swift
We need to test GiniHealthSDK and GiniMerchantSDK especially opening the banking apps from Merchant and Health Example
> PM-94: iOS 18 preparations

- .github/workflows/bank-api-library.check.yml
- .github/workflows/bank-sdk.check.yml
- .github/workflows/capture-sdk.build.docs.yml
- .github/workflows/capture-sdk.check.yml
- .github/workflows/health-api-library.build.docs.yml
- .github/workflows/health-api-library.check.yml
- .github/workflows/health-sdk.build.docs.yml
- .github/workflows/health-sdk.check.yml
- .github/workflows/merchant-sdk.build.docs.yml
- .github/workflows/merchant-sdk.check.yml
> ci: Change push triggers to pull_request

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceSkonto/DigitalInvoiceSkontoViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Models/SkontoViewModel.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoWithDiscountHeaderView.swift
> feat(GiniBankSDK): Remove "With Skonto discount" switch from the Skonto screen when coming from RA flow

- .github/workflows/bank-api-library.check.yml
- .github/workflows/capture-sdk.check.yml
- .github/workflows/health-api-library.check.yml
- .github/workflows/health-sdk.check.yml
- .github/workflows/merchant-sdk.check.yml
> ci: Remove matrix from concurrency

- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/GiniQRCodeDocumentTests.swift
Forgot to add test to the previous PR
> EC-130 add test

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewModel.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Models/DigitalInvoice.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Models/SkontoViewModel.swift
> feat(GiniBankSDK): recalculate max price value for Skonto RA items

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoWithDiscountHeaderView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoWithoutDiscountView.swift
> fix(GiniBankSDK): Fix UI bug for "Without skonto" and "With skonto" texts

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Models/Price.swift
> fix(GiniBankSDK): Fix decimal rounding for Price

- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample.xcodeproj/project.pbxproj
> fix(GiniHealthAPILibrary): Fix uncommitted files in GiniHealthSDK

- BankAPILibrary/GiniBankAPILibraryExample/GiniBankAPILibraryExampleTests/TransferSummaryIntegrationTest.swift
- BankAPILibrary/GiniBankAPILibraryPinningExample/GiniBankAPILibraryPinningExampleTests/TransferSummaryIntegrationTest.swift
- BankSDK/GiniBankSDKExample/Tests/IntegrationTests/DigitalInvoice/DigitalInvoiceIntegrationTests.swift
- BankSDK/GiniBankSDKExample/Tests/IntegrationTests/DigitalInvoiceWithSkonto/DigitalInvoiceWithSkontoIntegrationTests.swift
- BankSDK/GiniBankSDKExample/Tests/IntegrationTests/Skonto/SkontoIntegrationTests.swift
- BankSDK/GiniBankSDKExample/Tests/IntegrationTests/TransferSummary/TransferSummaryIntegrationTest.swift
- BankSDK/GiniBankSDKPinningExample/Tests/TransferSummaryIntegrationTest.swift
- CaptureSDK/GiniCaptureSDKExample/Tests/TransferSummaryIntegrationTest.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExampleTests/UploadDocumentsTests.swift
I have left comment here:
https://ginis.atlassian.net/browse/PP-141
> ci: Change tests timeout

- .github/publish_to_firebase.sh
- .github/workflows/bank-sdk.publish.example.app.firebase.yml
- .github/workflows/health-sdk.publish.example.apps.firebase.yml
- .github/workflows/merchant-sdk.publish.example.apps.firebase.yml
Here is a proof of work.
https://github.com/gini/gini-mobile-ios/actions/runs/12178796096/job/33970532545
> Pp 74 jira comment

- .github/workflows/health-sdk.publish.example.apps.firebase.yml
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/Adapter/Mapping.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
> Fix mapping for Document using a document link not extractions

- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReviewContainer/PaymentReviewContainerView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/TextField/TextFieldWithLabelView.swift
> fix(GiniHealthSDK): Fix numpad keyboard for changing amount

- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth+PaymentComponentsConfigurationProvider.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthConfiguration.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/DebugMenuViewController.swift
Return configuration option for showPaymentReviewCloseButton
> Ipc 548 payment review close button

- HealthSDK/GiniHealthSDK/Documentation/source/Integration.md
> fix(GiniHealthSDK): Fix integration guide for multiple invoices in a document

- GiniComponents/GiniInternalPaymentSDK/Package-release.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/GiniInternalPaymentSDKVersion.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/GiniUtilitesVersion.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Package-release.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
> chore(GiniUtilites,GiniInternalPaymentSDK, GiniHelathSDK): Bumps version

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/DocumentPagesPreview/DocumentPagesViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceSkontoTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceSkonto/DigitalInvoiceSkontoViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Components/PriceTextField.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Models/SkontoEdgeCase.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Models/SkontoViewModel.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAmountToPayView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoExpiryDateView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoWithDiscountHeaderView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoWithDiscountPriceView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoWithoutDiscountPriceView.swift
- BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/Skonto/PriceTextFieldTests.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorType.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/GiniAnalyticsEvent.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/GiniAnalyticsProperties.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/GiniAnalyticsScreen.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Tracking/Models/GiniErrorAnalytics.swift
> Pp 926 implement user journey analytics for skonto

- .github/workflows/bank-sdk.publish.example.app.firebase.yml
- .github/workflows/health-sdk.publish.example.apps.firebase.yml
- .github/workflows/merchant-sdk.publish.example.apps.firebase.yml
> PM-139 : Improving ci workflow

- BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/GiniBankAPI.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift
- BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/NetworkingScreenApiCoordinatorTests.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/DemoViewController.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/DemoViewController.xib
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController+SwitchOptionModel.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewModel.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
> fix(GiniBankSDK): Expose cancel sdk function 

- .github/workflows/bank-sdk.publish.example.app.firebase.yml
- .github/workflows/health-sdk.publish.example.apps.firebase.yml
- .github/workflows/merchant-sdk.publish.example.apps.firebase.yml
Improvement for extraction of Jira ticket 
PM-151
> Pm 151 jira ticket extraction improvements

- .github/workflows/health-sdk.publish.example.apps.firebase.yml
Remove check from the example app upload workflow IPC-572
> ci: Remove check from the example app upload workflow

- .github/workflows/bank-sdk.publish.example.app.firebase.yml
- .github/workflows/health-sdk.publish.example.apps.firebase.yml
- .github/workflows/merchant-sdk.publish.example.apps.firebase.yml
This fix will allow the job to pass even if there is no ticket found in the last 3 commits.
> ci: Fix jira ticket extraction when we don't find any ticket in the last 3 commits

- GiniComponents/GiniInternalPaymentSDK/Package-release.swift
- HealthAPILibrary/GiniHealthAPILibrary/Documentation/source/Installation.md
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Package-release.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
> RC HealthSDK 5.3.0

- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/de.lproj/Localizable.strings
> fix(GiniHealthSDK): Fix typo SIE

- RELEASE-ORDER.md
doc: Update release order PM-160
> doc: Update release order

- GiniComponents/GiniInternalPaymentSDK/Package-release.swift
- HealthAPILibrary/GiniHealthAPILibrary/Documentation/source/Installation.md
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Package-release.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
- HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/OrdersList/OrderListViewModel.swift
> RC HealthSDK 5.4.0

- BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController+SwitchOptionModel.swift
> fix(GiniBankSDKExample): Remove duplicated use case

- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Payments/Payment.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/PaymentTests.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Integration.md
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/GiniHealthTests.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/MockHelpers/MockSessionManager.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/Resources/payment.json
> feat(GiniHealthSDK): Expose getting payment

- GiniComponents/GiniInternalPaymentSDK/Package-release.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/GiniInternalPaymentSDKVersion.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/GiniUtilitesVersion.swift
- HealthAPILibrary/GiniHealthAPILibrary/Documentation/source/Installation.md
- HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Customization guide.md
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Package-release.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
> RC HealthSDK 5.5.0

- HealthSDK/GiniHealthSDK/Documentation/source/Customization guide.md
> fix(GiniHealthSDK): Fix customization documentation

- BankSDK/GiniBankSDKExample/Tests/IntegrationTests/BankAPILibrary/BankAPILibraryIntegrationTests.swift
- BankSDK/GiniBankSDKPinningExample/Tests/BankAPILibraryPinning/GiniBankAPILibraryPinningIntegrationTests.swift
- BankSDK/GiniBankSDKPinningExample/Tests/BankAPILibraryPinning/GiniBankAPILibraryPinningIntegrationWrongCertificatesTests.swift
Fix for the payment request test that is failing in the bank SDK tests.
> fix(GiniBankSDKExample): Fix integration test for payment request

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/ImagePickerCollectionViewCell.swift
> fix(GiniBankSDK): Voice over: User can't upload photos from Gallery

- BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/Resource.swift
- BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/SessionManager.swift
- BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/APIResourceTests.swift
- BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/PaymentTests.swift
- BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/SessionManagerMock.swift
- BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/UserResourceTests.swift
> fix(GiniBankSDK): Make url options so it wouldn't crash on invalid components

- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController+Helpers.swift
> fix(GiniHealthSDK): Health SDK wrong navigation to More Info screen

- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReviewContainer/PaymentReviewContainerView.swift
> feature(GiniInternalPaymentSDK): Change input IBAN input field from lowercase to uppercase automatically

- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/GiniInternalPaymentSDKVersion.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController+UICollection.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReviewContainer/PaymentReviewContainerView.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Package-release.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController+Helpers.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
> RC HealthSDK 5.5.1

- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BanksView/BanksBottomView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BanksView/BanksBottomViewModel.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BottomSheet/BottomSheetViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo/PaymentInfoViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController+PaymentReviewViewModelDelegate.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReviewContainer/PaymentReviewContainerView.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/Extensions/UIViewController+Extensions.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController+Helpers.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/MockHelpers/MockPaymentComponents.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/PaymentComponentsControllerTests.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponentsController.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/MockHelpers/MockPaymentComponents.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/PaymentComponentsControllerTests.swift
> fix(GiniHealthSDK): Bank picker is unresponsive on "barcode" flow

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
In this pr the navigation is fixed when a QR code is scanned successfully.
> Fix qrcode flow navigation

- GiniComponents/GiniInternalPaymentSDK/Package-release.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BanksView/BanksBottomView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BanksView/BanksBottomViewModel.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BottomSheet/BottomSheetViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/GiniInternalPaymentSDKVersion.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo/PaymentInfoViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReviewContainer/PaymentReviewContainerView.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/Extensions/UIViewController+Extensions.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/GiniUtilitesVersion.swift
- HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
- HealthSDK/GiniHealthSDK/Package-release.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController+Helpers.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/MockHelpers/MockPaymentComponents.swift
- HealthSDK/GiniHealthSDK/Tests/GiniHealthSDKTests/PaymentComponentsControllerTests.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponentsController.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/MockHelpers/MockPaymentComponents.swift
- MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/PaymentComponentsControllerTests.swift
> RC HealthSDK 5.5.2

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/QRCodeOverlay.swift
> feat(GiniCaptureSDK): QR code education edge cases

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/DocumentPages/Error/ErrorHeaderView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Help/Views/SkontoHelpItemView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoDocumentPreviewView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoExpiryDateView.swift
- BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/IBANDetectionOverlay/IBANDetectionOverlay.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingDataSource.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewCollectionCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
> feature(GiniCaptureSDK): Voice Over for BankSDK

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
> feat(GiniBankSDK): Update title for english

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoExpiryDateView.swift
> PP-1347 Revert change for external keyboard

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceAddOnListView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsViewContainer.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraNotAuthorizedView.swift
Updating in more places the dark7 to light 6 and using dark6 in light mode.
> Contrast issues fixes

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/PriceLabelView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemViewController.swift
> Pp 1415 ra edit 200

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Custom Views/GiniInputAccessoryView/GiniInputAccessoryView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Custom Views/GiniInputAccessoryView/GiniInputAccessoryViewConfigurable.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Custom Views/GiniInputAccessoryView/GiniInputAccessoryViewPresentable.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceProceedView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceSkontoTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceSkonto/DigitalInvoiceSkontoViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/NameLabelView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/PriceLabelView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/QuantityView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Help/DigitalInvoiceHelpSectionView.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
> Pp 1410 RA Voiceover

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceAddOnListCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalInvoiceSkontoTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCellViewModel.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift
- This PR updates the RA screen to support the physical keyboard functionality by disabling the focus of the cell to be able to reach the inner elements.
> Pp 1437 toggle and edit not reachable by keyboard

- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/IBANDetectionOverlay/IBANDetectionOverlay.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/QRCodeOverlay.swift
> Pp 1400 iban qr overlay overlapes 200

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemViewController.swift
> PP-1447 RA Edit Article bottom sheet landscape mode - keypad is closing while user is typing

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift
> fix(GiniBankSDK): reload data on invoice

- HealthSDK/GiniHealthSDK/.jazzy.yaml
- HealthSDK/GiniHealthSDK/Documentation/source/Accessibility guide.md
- HealthSDK/GiniHealthSDK/Documentation/source/Integration.md
-  Cleanup of Integration guide due to the confusing integration steps reported by the customer
-  Added accessibility guide (copied from the https://gini.atlassian.net/wiki/spaces/IBSV/pages/52101123/Accessibility)
- Closes [IPC-744](https://ginis.atlassian.net/browse/IPC-744?atlOrigin=eyJpIjoiYzEzYmVjYmYxODFiNDQ1YjliZjdiNzI5YzkzZDczMTEiLCJwIjoiaiJ9)
[IPC-744]: https://ginis.atlassian.net/browse/IPC-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ipc 744 docs

- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BanksView/BankSelectionTableViewCell.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BanksView/BanksBottomView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BottomSheet/BottomSheetViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/InstallApp/InstallAppBottomView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentComponents/PaymentComponentBottomView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentComponents/PaymentComponentView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentComponents/PaymentComponentsConfiguration.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo/PaymentInfoQuestionHeaderViewCell.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewConfiguration.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewModel.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/ShareInvoice/ShareInvoiceBottomView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/TextField/TextFieldWithLabelView.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/Protocols/BottomSheetPresentable.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/Protocols/GiniBottomSheetPresentable.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/Views/AccesibleView.swift
- GiniComponents/GiniUtilites/Sources/GiniUtilites/Views/AccessibleView.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth+PaymentComponentsStringsProvider.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController+Helpers.swift
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/de.lproj/Localizable.strings
- HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/en.lproj/Localizable.strings
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant+PaymentComponentsStringsProvider.swift
- MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponentsController.swift
- MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/OrderDetailViewController.swift
-This PR contains the fixes related to Voice Over for Health SDK. This has been done in a different branch to avoid making the 200% branch bigger. Also because voice over is not related to 200%
[IPC-540]
<!--
- Last bottomSheet moved to native `PaymentComponentBottomView`
- Added missing alternative texts
- Tested on Simulator: iPhone SE, iPhone 16e, iPhone 7 Plus
- Tested on Physical device: iPhone 13 Pro Max
[IPC-540]: https://ginis.atlassian.net/browse/IPC-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ipc 540 fix voiceover

- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/InstallApp/InstallAppBottomView.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController.swift
- GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/ShareInvoice/ShareInvoiceBottomView.swift
This PR fixes the issues found on RC build. 
[IPC-719]
[IPC-719]: https://ginis.atlassian.net/browse/IPC-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ipc 719 rc bug fixes

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewController.swift
- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoWithDiscountHeaderView.swift
This PR ensures that the Skonto screen on iPad properly supports Dynamic Type and can scale text up to 200% without any loss of content or functionality.
[PP-1361](https://ginis.atlassian.net/browse/PP-1361)
- Updated width constraints and layout logic to support larger text sizes.
- Tested different models of iPad
[PP-1361]: https://ginis.atlassian.net/browse/PP-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Pp 1361 skonto 200 ipad

- BankSDK/GiniBankSDK/.jazzy.yaml
- CaptureSDK/GiniCaptureSDK/.jazzy.yaml
This PR updates iOS simulator configurations for documentation generation from iOS 17.5 with iPhone 15 to iOS 18.5 with iPhone 16 across the SDK projects.
> ci: Update simulator OS version

- BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingHorizontalItem.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIDevice.swift
This PR moves subview and constraint setup from layoutSubviews to dedicated setupView() and setupConstraints() methods, improving stability and preventing multiple constraint activations. It also adds a UIDevice.isNonNotchSmallScreen check to adapt the layout for smaller devices.
[PP-1452](https://ginis.atlassian.net/browse/PP-1452)
- Removed subview and constraint setup from layoutSubviews
- Added setupView() and setupConstraints() called during init
- Used UIDevice.isNonNotchSmallScreen to adapt layout
- Hide topImageView on small screens 
- Added helper function isNonNotchSmallScreen to the UIDevice extension
[PP-1452]: https://ginis.atlassian.net/browse/PP-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Pp 1452 ra onboarding issue

- BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/Utils.swift
- BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/String+UtilsTests.swift
- BankSDK/GiniBankSDKPinningExample/Tests/TransferSummaryIntegrationTest.swift
- CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/PreferredButtonResource.swift
- CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/GiniCaptureDocumentValidatorTests.swift
- HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/Utils.swift
[PP-1689](https://ginis.atlassian.net/browse/PP-1689)
This PR addresses SonarQube code quality issues by replacing unsafe try! usages with safer error handling across the codebase. The changes improve code safety, readability, and maintainability while resolving static analysis warnings.
- Replaced all try! usages with try? combined with guard statements to handle potential failures safely
- Added clear failure messages where appropriate (e.g., in test data loading)
- Removed trailing spaces and minor formatting inconsistencies
- Enhanced code robustness and developer understanding of error handling
[PP-1689]: https://ginis.atlassian.net/browse/PP-1689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Pp 1689 sonar qube refactor safe error handling instead of try!
