BankAPILibrary/GiniBankAPILibrary/Documentation/sections/Documentation.md
BankAPILibrary/GiniBankAPILibrary/Documentation/source/Installation.md
BankAPILibrary/GiniBankAPILibrary/README.md
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/GiniBankAPILibraryVersion.swift
BankAPILibrary/GiniBankAPILibraryPinning/Package-release.swift
BankAPILibrary/GiniBankAPILibraryPinning/README.md
BankAPILibrary/GiniBankAPILibraryPinning/Sources/GiniBankAPILibraryPinning/GiniBankAPILibraryPinningVersion.swift
BankSDK/GiniBankSDK/Documentation/source/Installation.md
BankSDK/GiniBankSDK/Package-release.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDKVersion.swift
BankSDK/GiniBankSDKPinning/Package-release.swift
BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinningVersion.swift
CaptureSDK/GiniCaptureSDK/Documentation/source/Installation.md
CaptureSDK/GiniCaptureSDK/Package-release.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDKVersion.swift
CaptureSDK/GiniCaptureSDKPinning/Package-release.swift
CaptureSDK/GiniCaptureSDKPinning/Sources/GiniCaptureSDKPinningVersion.swift
HealthAPILibrary/GiniHealthAPILibrary/Documentation/source/Installation.md
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/GiniHealthAPILibraryVersion.swift
HealthAPILibrary/GiniHealthAPILibraryPinning/Package-release.swift
HealthAPILibrary/GiniHealthAPILibraryPinning/Sources/GiniHealthAPILibraryPinning/GiniHealthAPILibraryPinningVersion.swift
HealthSDK/GiniHealthSDK/Documentation/source/Installation.md
HealthSDK/GiniHealthSDK/Package-release.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/GiniHealthSDKVersion.swift
HealthSDK/GiniHealthSDKPinning/Package-release.swift
HealthSDK/GiniHealthSDKPinning/Sources/GiniHealthSDKPinning/GiniHealthSDKPinningVersion.swift

• Use 1.0.0 version for new libs and SDKs:
-  Health API Library;
-  Bank API Library;
-  Health SDK.
• Bump minor in the current version of existing libs and SDKs 1.1.0:
- Capture SDK;
- Bank SDK.
• Fix versions in installation guides.

Pia 1983 release

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/AccountingDocumentService.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/DocumentService.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/DocumentServiceProtocol.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/Extensions/GiniCapture+GiniCaptureDelegate.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/GiniCaptureNetworkService.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/GiniNetworkingScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/AppDelegate.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/CustomMenuItemViewController.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/ResultTableViewController.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/ScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/UIViewController.swift
CaptureSDK/GiniCaptureSDKExample/Tests/AlbumsPickerViewControllerTests.swift
CaptureSDK/GiniCaptureSDKExample/UITests/GINIAnalysisUITests.swift
CaptureSDK/GiniCaptureSDKExample/UITests/GINICameraUITests.swift
CaptureSDK/GiniCaptureSDKExample/UITests/GINIReviewUITests.swift

Capture SDK:
- Add Screen API support with custom networking:
1.   Add default implementation`GiniCaptureNetworkService`;
2.   Add initializer in GiniCapture networking with non-optional `GiniCaptureNetworkService` parameter.
Capture SDK Example:
- Fix code style warnings and refactor protocol implementation into the extensions.

Pia 2146 network service

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoiceViewController.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DigitalInvoiceOnboarding.storyboard
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DigitalLineItemTableViewCell.xib

Since iOS 15 and Xcode 13 a crash started happening in UITableViewCells related to the autoresizing
masks. By removing `translatesAutoresizingMaskIntoConstraints="NO"` from the line item view cell
xib's (`DigitalLineItemTableViewCell.xib`) root view and shadow view the crash was fixed.
Solution source: https://stackoverflow.com/a/69439370/276129
Due to switching to Swift Packages some referenced classes in the storyboard and xib had to be
updated. Also getting the bundle instance had to be updated.

fix(GiniBankSDK): Fix Return Assistant storyboard and line item xib crashes

---

BankSDK/GiniBankSDK/Documentation/source/Integration.md
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDK/Documentation/source/Integration.md
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/AnalysisResult.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/GiniNetworkingScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/ScreenAPICoordinator.swift

* Add the Gini Bank API Library `Document` to the `AnalysisResult` in Capture SDK.
* Update both Capture SDK and Bank SDK to add the document to `AnalysisResult`, if available.
* Update example apps and documentation.

Pia 2279 expose document

---

HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewModel.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift

- Show `0,00` text in the amount field when the cursor is in the field https://ginis.atlassian.net/browse/PIA-2341
- Show non-empty check  and validation errors according to the rules https://ginis.atlassian.net/browse/PIA-2336
- Fix feedback sending -> used compound

Pia 2337 show errors

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBank.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExampleTests/ScreenAPICoordinator+UI_Only.swift

Fix: `Screen API - UI Only`: GiniBankConfiguration wasn't set properly for view controller initializers.
Please, search for `Search for `// MARK: Screen API - UI Only - GiniCaptureDelegate``  In the example app to test it.

Pia 2380 configuration fix

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/AlbumsHeaderView.swift

-  Extend bank configuration with `albumsScreenSelectMorePhotosTextColor`.
- Cleanup code comments:
- Removed `Pay` SDK mentions;
- Added `.` at the end of comments;
- Removed empty line when there was one line comment;
- Removed empty lines, which were separating code and its comment.

Pia 2420 configuration select photos

---

CaptureSDK/GiniCaptureSDKExample/Tests/ExtractionFeedbackIntegrationTest.swift

Moved the modification of the extractions and the feedback sending into the
`giniCaptureAnalysisDidFinishWith()` method of the `GiniCaptureResultsDelegate`.
This shows how most clients receive the extractions and how they can use the accompanying
`sendFeedbackBlock` closure.
PIA-1891

refactor(GiniCaptureSDK): Show feedback sending with the `GiniCaptureResultsDelegate` in the integration test

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
BankSDK/GiniBankSDK/Documentation/source/Integration.md
BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/AnalysisResult.swift

- GiniBankAPILibrary: Add `Document` and `Document.Links` public initializers allowing the use of a customized JSON structure.
- GiniBankSDKExample: Add manual initialization of pay4 extractions and line items.
Maybe I need to ask our backend team and check the critical default values for Document.

Pia 2483 document initializer

---

BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIImage.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/No results/ImageAnalysisNoResultsViewController.swift

- Add customization options: text color and corner radius for the backToCameraButton on the No Results and Capturing tips screens.
- Make a consistent icon and text highlight style for the back to the camera button.
- Update docs.

Pia 2524 back to camera button

---

BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/Supported formats/SupportedFormatsViewController.swift

- Allow customizing the support/nonsupport icons on the supported formats screen.

Pia 2526 supporting formats docs

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DeselectLineItemActionSheet.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/en.lproj/LocalizableCustomName.strings
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/No results/ImageAnalysisNoResultsViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewMainCollectionCell.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Multipage Review/MultipageReviewViewController.swift
CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/MultipageReviewViewControllerTests.swift
CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/ReviewViewControllerTests.swift

- Allow customizing the suggestions collection header, the warning text, the warning icon, the icon & the title for back to the camera for the No Results screen.
- Allow customizing the accessibility labels for the document image title and the rotate button title for the Multipage Review screen.
- Allow customizing the deselect action sheet title and cancel action title when you deselect line item.

Pia 2552 fix labels override

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings
BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
BankSDK/GiniBankSDKExample/GiniBankSDKExample/de.lproj/LocalizableCustomName.strings
BankSDK/GiniBankSDKExample/GiniBankSDKExample/en.lproj/LocalizableCustomName.strings
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/AnalysisStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/CameraStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/GalleryStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/HelpStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/ImageAnalysisNoResultsStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/MultipageReviewStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/NavigationBarStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/OnboardingStrings.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/ReviewStrings.swift

- Allow text customising for capturedImagesStackSubtitleLabel, popupTitleImportPDF, popupTitleImportPDForPhotos, popupOptionPhotos, popupOptionFiles, popupCancel on the camera screen.
- Allow text customising for imagePickerOpenButton on the gallery screen.
- Allow text customising for addButtonLabel, navigation titleMessage on the multipage review screen.
- Allow text customising for collectionHeaderText, goToCameraButton, warningText
on the no results screen and warningHelpMenuText and titleText for the capturing tips screen.
- Allow text customisation for supported formats screen and title for the open with screen.
- Fix default analysis error text for the analysis screen.
- Remove duplicated text customization options for menu items.
- Remove duplicated customization options for …

Add localisation fixes 

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/LineItemDetailsViewController.swift

Uses configuration flag `enableReturnReasons` for showing/hiding return reasons dialog on line items details screen.
PIA-2730

PIA-2730_disable_return_reason

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/ReturnAssistantConfiguration.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/UIFont+Utils.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIFont.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniCaptureFont.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/AppCoordinator.swift

GiniCaptureSDK, GiniBankSDK: 
- Adds default text style fonts,
- Allows customization of a specific text style.
- Add depreciation for old `customFont` property.

Pia 2865 fonts

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera.swift

CameraViewController - Remove deprecated delegate function
The function I deleted is deprecated and not used according to the [Apple documentation](https://developer.apple.com/documentation/avfoundation/avcapturephotocapturedelegate/1778647-photooutput)

PIA-2903 pr

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppCoordinator.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/CustomLoadingIndicator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/OnButtonLoadingIndicatorAdapter.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings

Add custom loading indicator. 
Uncomment lines 92-92 in GiniBankSDKExample - Appcoordinator to test the custom loading

Pia 3182 add a loading indicator for the last added page on the analysis screen

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniImageDocument.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Analysis.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/GiniScreenAPICoordinatorTests.swift

When opening an image from another app(Files for ex.) the Review screen should be skipped and if an error occurs on analysis, the No results screen's cancel button should close the flow, not go back to the review.

Pia 3260 skip review screen for images received from another app via open with

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift

fix(GiniCaptureSDK): Fix layout with bottom navigation

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift

If you enable QRCode Scan ONLY but disable QR code scanning, nothing should happen.

Fix QR code scanning only if flag of QR reading is disabled

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraPane.swift

Fix flash toggle hiding when flag is set from config. 
Please test it on a device with no flash. I don't have any right now.

fix(GiniCaptureSDK): Fix flash toggle apperance

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/ExtractionResult.swift
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/ExtractionsContainer.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/ExtractionsContainerTest.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
BankSDK/GiniBankSDKExample/Tests/ExtractionFeedbackIntegrationTest.swift
BankSDK/GiniBankSDKPinningExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
BankSDK/GiniBankSDKPinningExample/Tests/ExtractionFeedbackIntegrationTest.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/AnalysisResult.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/GiniNetworkingScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDKExample/Tests/ExtractionFeedbackIntegrationTest.swift
CaptureSDK/GiniCaptureSDKPinningExample/Tests/ExtractionFeedbackIntegrationTest.swift

I exposed a field through `AnalysisResult` to allow clients to get the extraction candidates.
Extraction candidates contain all identified extractions, for example if the invoice has three IBANs all of them will be added to the extraction candidates. One of them is picked as the main extraction, but clients may want to use one of the candidates instead.

Pia 3162 expose extraction candidates

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DeselectLineItemActionSheet.swift

When you change the tint color to red:

fix(GiniBankSDK): Add tint color for action sheet

---

.github/workflows/bank-api-library.build.docs.yml
.github/workflows/bank-api-library.check.yml
.github/workflows/bank-api-library.publish.docs.yml
.github/workflows/bank-api-library.release.yml
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/APIResource.swift
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/Auth/UserResource.swift
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/GiniBankAPI.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/APIResourceTests.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/UserResourceTests.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj

Changes for version 1.x.
Example of how to set the path when using the Bank SDK:
```swift
let viewController = GiniBank.viewController(withClient: client,
configuration: configuration,
resultsDelegate: self,
api: .custom(domain: "scan2bank-service-v1-scan2bank-itu.apps.caas-ekad-test01.rz.bankenit.de",
path: "/rest/de.fiduciagad.scan2bank.api.v1.Scan2BankApi"), 
tokenSource: nil)
```

Pia 3986 allow path in custom base url

---

BankSDK/GiniBankSDKExample/GiniBankSDKExample/Base.lproj/Main.storyboard
BankSDK/GiniBankSDKExample/GiniBankSDKExample/ResultTableViewController.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/Base.lproj/Main.storyboard
CaptureSDK/GiniCaptureSDKExample/Example Swift/ResultTableViewController.swift
CaptureSDK/GiniCaptureSDKExample/Example Swift/ScreenAPICoordinator.swift

Fix for text enlargement on the result screen for Capture and Bank SDK examples as well.

Pia 3718 ios there is no enlarging of text if larger text of accessibility is enabled

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/QuantityView.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Help/DigitalInvoiceHelpViewController.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift

For customizing the localizable strings from GiniBankSDK we use "NSLocalizedStringPreferredGiniBankFormat" Remove unused title for the Digital Invoice Onboarding screen
PIA-4034

fix(GiniBankSDK): Fix localization for the Return Assistant strings

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Model/LineItem.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/Array.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniImageDocument.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/CameraLensSwitcherView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/GalleryCoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/DataSources/HelpFormatsDataSource.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewViewController.swift

chores: Fix swiftlint warnings
- added enable rule for the ones that were missing after disabling them 
Remains to be fixed other two warnings:
`// swiftlint:disable force_cast` - we can discuss later
`// swiftlint:disable implicit_getter` - I have a suggestion to fix this

chores: Fix swiftlint warnings

---

BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
BankSDK/GiniBankSDKPinningExample/GiniBankSDKExample/en.lproj/LocalizableCustomName.strings
CaptureSDK/GiniCaptureSDK/Documentation/source/Customization guide.md
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/Camera2ViewController.swift

- Use "Scan a QR code" as navigation bar title when in QR code only mode on phones, too
- Add new Figma files [link](https://www.figma.com/file/z2naLjqFknlrlbHhfAWx85/iOS-Gini-Bank-SDK-3.1.2-UI-Customisation?type=design&t=Os5z2xZU9Es03FVo-0) and [link](https://www.figma.com/file/hxgxewJy4t08Pb0qK2TbxA/iOS-Gini-Capture-SDK-3.1.2-UI-Customisation?type=design&node-id=0-1&t=fC2mAMhelRFkeveT-0)
- Update links in `Customisation guide`

Pia 4109 navigation title qrcode only

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/ReuseIdentifier.swift

Hide extension UITableViewCell: ReuseIdentifiable {}
Customers had the compile issues about it.
PIA-4192

fix(GiniCaptureSDK): Hide extension UITableViewCell: ReuseIdentifiable {}

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/GiniNetworkingScreenAPICoordinator.swift

Fix the display of the error screen on the main thread after the server returned the error
PIA-4271

fix(GiniCaptureSDK): Fix the display of the error screen on the main thread after the server returned the error

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Utils.swift

fix(GiniCaptureSDK): Removed open override `layoutSubviews`
It is corrupting the table view layout where UITableViewCell was used
PIA-4381
The original commit message was: `fix(GiniCaptureSDK): fix layouting issues in help format screen PIA-3134`
https://ginis.atlassian.net/browse/PIA-3134

fix(GiniCaptureSDK): Removed open override `layoutSubviews`

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/PrivacyInfo.xcprivacy
BankAPILibrary/GiniBankAPILibraryPinning/Sources/GiniBankAPILibraryPinning/PrivacyInfo.xcprivacy
BankSDK/GiniBankSDK/Sources/GiniBankSDK/PrivacyInfo.xcprivacy
BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinning/PrivacyInfo.xcprivacy
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/PrivacyInfo.xcprivacy
CaptureSDK/GiniCaptureSDKPinning/Sources/GiniCaptureSDKPinning/PrivacyInfo.xcprivacy

- Add PrivacyInfo manifest file to all Gini sdks

Pia 4300 add privacy manifest v1

---

.github/workflows/bank-sdk.build.xcframeworks.yml
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankUtils.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/GiniCaptureUtils.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/PreferredButtonResource.swift

Add the possibility of having a custom bundle for images and localizable strings.
In order to test this please use the project from this repro https://github.com/gini/cocoapods-xcframework-tester/tree/PIA-2548-test-project . It should contain everything that is needed to test.

Pia 2548 custom bundle

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift

Divider added on top of the `ButtonContainerView`
PIA-4364

fix(GiniBankSDK): Add missing divider between total view and the digital invoice content

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/ImagePickerViewController.swift

- the real issue was that the Gallery screen was not scrolled automatically to the bottom of the list where the recent images are displayed
- the issue was happening starting with iOS 15
- is not an issue on SDK version 1.x.x
PIA-4546

fix(GiniCaptureSDK): Fix how the pictures are displayed in the Gallery screen

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/DocumentPickerCoordinator.swift

fix(GiniCaptureSDK): Remove unused Gini configuration option
- `documentPickerNavigationBarTintColor` was removed from the configuration since is not needed
- additional cleanup was done
PIA-4442

PIA-4545-iOS-Headlines-on-DKB

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/Auth/Token.swift
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/PartialDocumentInfo.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/AccessTokenTests.swift
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/Auth/Token.swift
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/PartialDocumentInfo.swift
HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/AccessTokenTests.swift

fix(GiniBankAPILibrary, GiniHealthAPILibrary): Fix the optional response fields that are decoded as required
- fixes the `scope` and the `type` properties in `Token` object to be decoded as optional
- fixes the `document` property in `PartialDocumentInfo` object to be decoded as optional
- add extra  unit tests
PIA-4592

PIA-4592  Optional response fields are decoded as required

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController+SwitchOptionModel.swift
BankSDK/GiniBankSDKExample/Tests/SettingsViewControllerTests.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift

- make `flashOnByDefault` disabled by default when the SDK starts
- adjust the name of the two settings options in the Settings screen related to flash
BSDK-94

Bsdk 94 make flash off by default

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift

- rounded corners and the separator visibility need to be reset to their default values when reusing cells after the call of `tableView.reloadData()`
BSDK-163

fix(GiniBankSDK): Fix UI issues in Digital Invoice screen after disabling one item

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift

- RA flow -> after coming back from the help screen, the digital invoice onboarding screen should not be displayed
BSDK-222

fix(GiniBankSDK): Fix the displaying of the digital invoice onboarding screen

---

.github/workflows/bank-sdk.release.yml

I assumed that we're missing some credentials there
BSDK-263

ci(project): Fix XCFramework generation in release workflow.

---

BankSDK/GiniBankSDK/Pod/GiniBankSDK.podspec
BankSDK/GiniBankSDK/Pod/README.md
BankSDK/GiniBankSDKPinning/Pod/GiniBankSDKPinning.podspec
BankSDK/GiniBankSDKPinning/Pod/README.md
fastlane/Fastfile
fastlane/README.md

- add a Readme file with manual steps for how to release a new version of podspecs in `gini-podspecs`
- add an example of `podspecs` file 
- create a Fastlane lane to generate release podspecs with the release version
**Steps to test this locally**:
- add the folder with the needed frameworks for GiniBankSDK(GiniBankSDK, GiniBankApiLibrary, and GiniCaptureSDK) in the recently added folder `Pod` which can be found in the `GiniBankSDK` folder from `BankSDK` from the main folder of the project
- locate the local path for this folder from your computer
- locate the local path for the `gini-podspecs` repo from your computer
- pod_name: name of the `podspecs` file 
-  template_podspec_path : path to the template podspec file from the local clone of the mono repo project, which is modified and …

Bsdk 35 create fastlane lane to generate release podspecs with the release version

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/Auth/SessionManager+Auth.swift
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/GiniError.swift
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/KeyStore.swift
BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/SessionManager.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift

- Fixes anonymous user to log in again after each GiniBankApiLibrary launch
- cleanup code

Bsdk 27 anonymous user not logged in again after each ios gini bank api library launch

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/Auth/SessionManager+Auth.swift
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Core/Auth/SessionManager+Auth.swift
HealthAPILibrary/GiniHealthAPILibraryPinningExample/GiniHealthAPILibraryPinningExampleTests/GiniHealthAPILibraryPinningIntegrationWrongCertificatesTests.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKPinningExampleTests/GiniHealthSDKPinningExampleWrongCertificatesTests.swift

Fix the error type when fetching the user access token so the error is not `unauthorized` one and tests

PP 67 Mapping of error messages with api defined status codes

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/de.lproj/Localizable.strings
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/en.lproj/Localizable.strings

- add missing "?" for `ginibank.digitalinvoice.help.title2`
- add german text for `Total` -> `Gesamtpreis`
- fix `ginibank.digitalinvoice.help.description3` typo
- fix english text for gift card
PP-329

fix(GiniBankSDK): Fix typos in Digital invoice screen

---

HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Payments/PaymentProvider.swift
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Payments/PaymentProviderResponse.swift
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Payments/PaymentService.swift
HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/Resources/provider.json
HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/Resources/providers.json
HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/Utils.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentInfo.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewModel.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift

IPC-161
https://ginis.atlassian.net/browse/IPC-161

feat(GiniHealthSDK): Payment provider universal link to launch the payment provider app IPC-161

---

BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/UserTests.swift
HealthAPILibrary/GiniHealthAPILibrary/Tests/GiniHealthAPILibraryTests/UserTests.swift

Fix user encode tests:
We've been checking struct encoding vs constant string - tests were not reliable.

Fix user encode tests

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/Components/QuantityView.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/BottomLabelButton.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/FileImportButtonView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/GiniBarButton.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/MultilineTitleButton.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/PreferredButtonResource.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraLensSwitcherView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraNotAuthorizedView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraPane.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/ThumbnailView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/Gallery/AlbumsHeaderView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/Views/OnboardingBottomNavigationBar.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewCollectionCell.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewZoomViewController.swift

By setting `isExclusiveTouch` to `true`, we ensure that only one touch event is recognized at a time on that particular UI element.

Pp 422 tapping the help button multiple times before the camera is active help screen is pushed multiple times

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Screen API Coordinator/GiniScreenAPICoordinator+Camera.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Networking/DocumentService.swift

- The QR code has priority even if the user already took some pictures and we should proceed with the QR code flow and no alert view should appear with the error message about types of files.
- Remove all the pages that have already been captured and keep the document generated after scanning the QR code

PP 400 user gets stuck in qr code detection analysis screen when multi pages are scanned

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Payments/PaymentService.swift
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/DocumentService.swift
HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/Payments/PaymentService.swift

While testing the Health API on stage I discovered that some requests were always using the default api domain instead of the custom one and so I had to apply these small fixes to be able to test on stage.

Pm 81 fix for custom api domain

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpMenuViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingDataSource.swift

Add missing property `has_custom_items ` to `screen_shown` event for all onboarding screens and fix the indentation.

Pp 387 add onboarding screen events

---

BankSDK/GiniBankSDKExample/GiniBankSDKShareExtension/Info.plist

- there was an error when trying to distribute via appstoreconnect due to an incorrect value type for the key `NSExtensionActivationSupportsImageWithMaxCount` in your Info.plist file This key expects a positive integer value, but currently, it has a string value.

fix(GiniBankSDKExample): Fix value type for the key `NSExtensionActivationSupportsImageWithMaxCount` in your Info.plist file

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/DigitalInvoiceViewController.swift

Sent `help_tapped` event from RA screen when `custom navigation bottom bar` is enabled
PP-582

fix(GiniBankSDK): Sent `help_tapped` event from RA screen when `custom navigation bottom bar` is enabled

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/PrivacyInfo.xcprivacy
BankSDK/GiniBankSDKPinning/Sources/GiniBankSDKPinning/PrivacyInfo.xcprivacy
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/PrivacyInfo.xcprivacy
CaptureSDK/GiniCaptureSDKPinning/Sources/GiniCaptureSDKPinning/PrivacyInfo.xcprivacy

Update privacy manifest files with tracking information:
Apple documentation:
"At the top level of this property list file, add the following keys to the dictionary:
NSPrivacyTracking
A Boolean that indicates whether your app or third-party SDK uses data for tracking as defined under the App Tracking Transparency framework. For more information, see [User Privacy and Data Use](https://developer.apple.com/app-store/user-privacy-and-data-use/).
NSPrivacyTrackingDomains
An array of strings that lists the internet domains your app or third-party SDK connects to that engage in tracking. If the user has not granted tracking permission through the App Tracking Transparency framework, network requests to these domains fail and your app receives an error.
**To provide a list of internet domains in …

PP 504 check if the privacy manifests needs to be updated

---

HealthSDK/GiniHealthSDK/Documentation/source/Integration.md
HealthSDK/GiniHealthSDK/Documentation/source/Testing.md

- Update `Integration guide`, the presentation for bottom sheets should happen without animation since SDK handles the animation during the presentation
- Fix images in `Testing guide`
IPC- 287

doc(GiniHealthSDK): 

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/Views/OnboardingPageCell.swift

Use `subheadline` style for the description labels on the onboarding screens
`We will need to update the customization guide (at least for Bank RA onboarding screen)`
PP-577, PP-468

fix(GiniCaptureSDK, GiniBankSDK): Use subheadline style for the description labels on the onboarding screens

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewModel.swift

Fix values sent in the modified `ExtractionResult` to be used by banking apps
Issue:

fix(GiniBankSDK): Fix values sent in the modified `ExtractionResult` to be used by banking apps

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/BottomNavigation/DefaultSkontoBottomNavigationBar.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewController.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAmountView.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAppliedDateView.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoAppliedHeaderView.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoNotAppliedView.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Views/SkontoProceedView.swift

Add updated iPad layout to be consistent with RA:
Update layout to support small devices

Pp 636 handle UI for small devices and i pads in skonto

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Models/GiniCaptureDocument.swift

I still didn't manage to catch the crash, but judging by the error from the video, I think we should just overwrite the writeContents method and make a check, similar to what is done in `loadFromContents` in `InputDocument` (as far as I understood it is used instead of the regular `UIDocument`).

PP-639: Attempt to fix the UIDocument crash

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UILabel.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/QRCodeOverlay.swift

I managed to replicate the issue on iPhone 6s iOS 15.8.2, but only with "QR code detected", with "Scan invoice or QR code" at the bottom everything is fine, and it already has minimumScaleFactor and adjustsFontSizeToFitWidth set up to it

PP-208 fix "qr code detected" getting cut off

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewController.swift

We introduced this bug when we added `hasShownAlert` to not show once again the alert for Skonto edge cases when coming back from Help.
PP-738

fix(GiniBankSDK): Fix the display of the Skonto edge case alert info view when tapping on the info banner view

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/OnboardingScreen/OnboardingViewController.xib

The reason was that in the storyboard of that button it didn't have any custom class, just UIButton, although in the code was MultilineTitleButton, it did not crash simply because there were no additional properties before adding GiniCaptureButton.
EXC_BAD_ACCESS with code 1 usually means that the object either does not exist in memory at all (either it was never allocated or it was freed), or the address of the memory location is crooked. In this case, because the class was not defined in the storyboard (so inside uikit the memory was allocated just for UIButton), the memory for traitCollectionUpdated was not allocated, even if you put nil as default value (and Optional != nullptr).
Sometimes EXC_BAD_ACCESS also occurs because of some bugs in xcode (so far I've seen it only with …

PP-802: Fix crash in storyboard

---

BankAPILibrary/GiniBankAPILibraryExample/GiniBankAPILibraryExampleTests/IntegrationTests.swift
BankAPILibrary/GiniBankAPILibraryPinningExample/GiniBankAPILibraryPinningExampleTests/GiniBankAPILibraryPinningIntegrationTests.swift

Update test, since resolved payment can't be resolved again

Fixed test for GiniBankAPiLibrary `resolvePayment`

---

GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewModel.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController+Helpers.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/Tracking/GiniHealthTrackingDelegate.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/InvoicesList/InvoicesListViewModel.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/OrdersList/OrderDetailViewController.swift
MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponentsController.swift

- Add tracking event  closebuttonClicked
- Fixed delegate event  didCreatePaymentRequest(paymentRequestId: String)
- Fixed delegate set in init(giniApiLib: GiniHealthAPI) used in init with AlternativeTokenSource

Ipc 551 fix delegate

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Document picker/DocumentPickerCoordinator.swift

fix buttons tint color in documentpicker when uibarbuttonitem appearance tint color is globally overridden
PP-733

fix(GiniBankSDK): fix buttons tint color in documentpicker

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemViewModel.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Models/SkontoDocumentPagesViewModel.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Models/SkontoViewModel.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/TransactionDocs/Components/TransactionDocsItemView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpFormatsViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpMenuViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Help/ViewControllers/HelpTipsViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/BottomButtonsViewModel.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingDataSource.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Onboarding/OnboardingViewController.swift

I can't build with Xcode 15 anymore ;(

Pp 981 lint

---

.github/workflows/bank-api-library.build.docs.yml
.github/workflows/bank-api-library.check.yml
.github/workflows/bank-sdk.build.docs.yml
.github/workflows/bank-sdk.check.yml
.github/workflows/capture-sdk.build.docs.yml
.github/workflows/capture-sdk.check.yml
.github/workflows/health-api-library.build.docs.yml
.github/workflows/health-api-library.check.yml
.github/workflows/health-sdk.build.docs.yml
.github/workflows/health-sdk.check.yml
.github/workflows/internal-payment-sdk.check.yml
.github/workflows/merchant-sdk.build.docs.yml
.github/workflows/merchant-sdk.check.yml
.github/workflows/utilites.check.yml

- the `edited` type was removed because we don't want to trigger the flows when the pr title or description is modified.
- `tags-ignore` does not apply to `workflow_dispatch` or `pull_request`

GitHub action workflows improvements

---

BankSDK/GiniBankSDKExample/GiniBankSDKExample/Utils/Device.swift

- Adjust layout to prevent the Transaction list button from overlapping with the `Photopayment` button on small-screen devices (e.g., iPhone SE, 6/7/8) PP-1057

fix(GiniBankSDKExample): Fix button overlap on main screen for specific small-screen devices

---

BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift

- The value of instant payment needs to be editable in the extractions screen of the demo app.
- Possible values should be "true" / "false".

PP-1097 Make `instantPayment` extraction editable in `TransactionSummary` screen

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/TransferSummary/TransferSummaryExtractionsTests.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/Screen API/ScreenAPICoordinator.swift
BankSDK/GiniBankSDKExample/Tests/IntegrationTests/Base/BaseIntegrationTest.swift
BankSDK/GiniBankSDKExample/Tests/IntegrationTests/TransferSummary/BaseIntegrationTest+TransferSummary.swift
BankSDK/GiniBankSDKExample/Tests/IntegrationTests/TransferSummary/TransferSummaryIntegrationTest.swift
BankSDK/GiniBankSDKExample/Tests/Resources/TransferSummary/result_Gini_invoice_example_payment_reference.json
BankSDK/GiniBankSDKExample/Tests/Resources/TransferSummary/result_Gini_invoice_example_payment_reference_after_feedback.json
BankSDK/GiniBankSDKPinningExample/Tests/TransferSummaryIntegrationTest.swift

Transfer summary for Instant Payment:
- Add `instantPayment` property to transfer summary method
- Add unit tests for transfer summary extractions
- Adjust integration tests

Pp 1099 transfer summary for instant payment

---

BankSDK/GiniBankSDKExample/Tests/IntegrationTests/TransferSummary/BaseIntegrationTest+TransferSummary.swift
BankSDK/GiniBankSDKExample/Tests/IntegrationTests/TransferSummary/TransferSummaryIntegrationTest.swift
BankSDK/GiniBankSDKPinningExample/Tests/TransferSummaryIntegrationTest.swift

Add a missing condition for the default value of instant payment.
For now, for every case that is not instant payment detected on the invoice or is on the invoice but not check marked, we receive from CVIE it as false

fix(GiniBankSDKExample): Fix integration test for instant payment feature when the default value is false

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Configuration/ClientConfiguration.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/ClientConfigurationTests.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/Resources/clientConfiguration.json
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
BankSDK/GiniBankSDKExample/Tests/IntegrationTests/ClientConfiguration/ClientConfigurationTests.swift

This pull request introduces a new boolean flag in the `ClientConfiguration` object. The flag allows us to control whether the QR code education message should be displayed.
The flag value is retrieved via the `/configurations` API endpoint.

Pp 1151 implement configuration flag qr code education message

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/EducationFlow/EducationFlowController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/EducationFlow/EducationFlowState.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Storage/GiniCaptureUserDefaultsStorage.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings
CaptureSDK/GiniCaptureSDK/Tests/GiniCaptureSDKTests/EducationFlowControllerTests.swift

Improves education message logic based on`fileImportSupportedTypes` and error handling
- Do not show any education message when DocumentImportEnabledFileTypes is NONE; fallback to the original loading indicator.
- Show the invoice education message ("Upload PDFs, images, or GIFs") when import types are enabled.
- On capture processing error, do not delay the response to ensure education message visibility. In this case, we do not mark the education message as "seen" by the user.
- In the case of the "No results" flow, we should display the education message for the full duration (4.5 seconds) before showing the "No results" screen.

Pp 1241 invoice edge case education concept

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/BottomNavigation/DefaultSkontoBottomNavigationBar.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Help/BottomNavigation/DefaultSkontoHelpNavigationBottomBar.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Help/SkontoHelpViewController.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/Help/Views/SkontoHelpItemView.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/SkontoViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/GiniBarButton.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Extensions/UIDevice.swift

Fix the bottom navigation bar in the Skonto screen in landscape.
Fix the custom bottom navigation bar in the Skonto screen in landscape
**Tested scenarios**:
- normal navigation bar(at the top of the screen)
- bottom bar navigation 
- custom bottom bar navigation
Switching from portrait to landscape and back, multiple times.
**Tested on the following devices:**
iPhoneSE first gen(iOS15.0)
iPhone 8(iOS 16.1)
iPhone 15 Pro(iOS 17.0.3)
iPad Air 11-ich (M2, iOS 18.3)

Pp 1311 skonto screen bottom bar missing when switching from portrait to landscape

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Custom views/GiniAnimatedSuffixLabelView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/EducationFlow/Views/QRCodeEducation/QRCodeEducationLoadingView.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/EducationFlow/Views/QRCodeEducation/QRCodeEducationLoadingViewModel.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/EducationFlow/Views/QRCodeEducation/QRCodeEducationPresenting.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/GiniAccessibility.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/CameraPreviewViewController.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraPane.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/IBANDetectionOverlay/IBANDetectionOverlay.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/QRCodeOverlay.swift
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/de.lproj/Localizable.strings
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Resources/en.lproj/Localizable.strings

Make QR Code Education accessible:
- landscape
- voice over
- font size 200%
When VoiceOver is enabled, the image, the text beneath it , and the analyzing animated text will be read aloud as a single element. The text that should be read is the one displayed directly below the image and the accessibility text for the animated loading text. Value of the animated loading text for voice over should be:  “analyzing invoice in progress” – “analyse der Rechnung läuft”.
Font size 200% tested on iPhone SE first gen simulator just on capture invoice flow:
https://github.com/user-attachments/assets/c162923a-4b17-409d-8faa-7ea13916c5d7
https://github.com/user-attachments/assets/58565d50-2d31-46e1-8a73-e276f5d35e16
https://github.com/user-attachments/assets/5ec34c1e-923f-40ea-85df-bc1d21f826d7

Pp 1398 make qr code education accessibility conform

---

BankSDK/GiniBankSDKExample/GiniBankSDKExample/Info.plist

Support opening XML files in app document types.
Adds `public.xml` to `CFBundleDocumentTypes` to enable XML file support.

PP-1442 E- invoice open with support in demo app

---

GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo/PaymentInfoConfiguration.swift
GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo/PaymentInfoQuestionHeaderViewCell.swift
GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentInfo/PaymentInfoViewModel.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth+PaymentComponentsConfigurationProvider.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthColors.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthConfiguration.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/GiniColors.xcassets/Accent01Dark.colorset/Contents.json
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/GiniColors.xcassets/Accent01Light.colorset/Contents.json
MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant+PaymentComponentsConfigurationProvider.swift

This PR consists of color-related changes across the Payment Info module. It introduces support for customizing the tint of question header icons and updates the accent01 color to adapt properly in both light and dark modes.
[IPC-513](https://ginis.atlassian.net/browse/IPC-513)
- Added tint color support for question header icons via configuration.
- Updated accent01 to use dynamic colors for light and dark appearance.
[IPC-513]: https://ginis.atlassian.net/browse/IPC-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ipc 513 contrast issue

---

GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReview/PaymentReviewViewController.swift
GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentReviewContainer/PaymentReviewContainerView.swift
GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PoweredByGini/PoweredByGiniView.swift
GiniComponents/GiniUtilites/Sources/GiniUtilites/Extensions/UIResponder+Extensions.swift

This PR fixes the issue related to inline errors not being displayed on `landscape mode` for `PaymentReviewScreen`
[IPC-747]
[IPC-747]: https://ginis.atlassian.net/browse/IPC-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ipc 747 inline error messages not displayed landscape

---

GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/InstallApp/InstallAppBottomView.swift
GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/ShareInvoice/ShareInvoiceBottomView.swift
GiniComponents/GiniUtilites/Sources/GiniUtilites/Protocols/GiniBottomSheetPresentable.swift

IPC-540
Fixed issue when user tap on sub view and it wont say anything
[IPC-540](https://ginis.atlassian.net/browse/IPC-540)
Updated setupAccessibility() to set accessibilityElements on the view instead of the view controller itself. This make sure VoiceOver can properly focus on and read each individual element.
[IPC-540]: https://ginis.atlassian.net/browse/IPC-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GiniHealthSDK): fixing voice over issue when user taps on label

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingHorizontalItem.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift

This addresses an accessibility issue on the onboarding screen for RA + Skonto. When using VoiceOver in landscape mode, the screen content is read out as if the app is still in portrait mode, causing confusion for users relying on accessibility support.
[PP-1450](https://ginis.atlassian.net/browse/PP-1450)
- Set accessibility elements based on orientation
- Fixed layout constraint breaking logs seen during orientation changes (visible in debug output)
- Removed SwiftLint warnings from the relevant classes
[PP-1450]: https://ginis.atlassian.net/browse/PP-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pp 1450 voice over skonto issue

---

BankAPILibrary/GiniBankAPILibrary/Documentation/sections/Documentation.md
BankAPILibrary/GiniBankAPILibrary/Documentation/source/Getting started.md

PP-1524
Updates the GiniBankAPILibrary public documentation generated with Jazzy. 
We needed to provide more examples of how the customers should set the networking part with their own authentication, using `AlternativeTokenSource`.
Also, some deprecated links were updated related to the Pay API public documentation.

fix(GiniBankAPILibrary):  Update the `GiniBankAPILibrary` public documentation

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
BankSDK/GiniBankSDK/Sources/GiniBankSDK/Resources/DigitalLineItemTableViewCell.xib
CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Review/ReviewCollectionCell.swift

Fix VoiceOver navigation issues in DigitalLineItemTableViewCell on iOS 15.
[PP-1441](https://ginis.atlassian.net/browse/PP-1441)
This PR addresses circular navigation issues with VoiceOver accessibility on iOS 15 in the DigitalLineItemTableViewCell. Users were unable to navigate from the edit button to the next table view cell, instead getting trapped in a loop between the edit button and price label. Or the switch button couldn't be reached while swiping when VoiceOver was enabled.
**Changes made:**
1. **Removed incorrect RTL semantic attribute**: Eliminated `semanticContentAttribute="forceRightToLeft"` from the edit button in XIB, which was causing VoiceOver navigation conflicts on iOS 15
2. **Added explicit accessibility element ordering**: Implemented `accessibilityElements` array to …

Pp 1441 ra voice over in iPad unable to select the toggle using swipe gesture

---

GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/BanksView/BanksBottomView.swift
GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentComponents/PaymentComponentBottomView.swift
GiniComponents/GiniInternalPaymentSDK/Sources/GiniInternalPaymentSDK/PaymentComponents/PaymentComponentViewModel.swift
GiniMobile.xcworkspace/xcshareddata/swiftpm/Package.resolved
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealth.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController+Helpers.swift
HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponentsController.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample.xcodeproj/project.pbxproj
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppCoordinator.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppDelegate.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/DebugMenuViewController.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/GoogleService-Info.plist
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/InvoicesList/InvoicesListCoordinator.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/InvoicesList/InvoicesListViewModel.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/OrdersList/OrderDetailViewController.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/OrdersList/OrderListCoordinator.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/OrdersList/OrderListViewController.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/OrdersList/OrderListViewModel.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/PrivacyInfo.xcprivacy
MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentComponentsController.swift
MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/OrderDetailViewController.swift

This PR add a new `delegate` to `HealthSDK` to notify to the consumer app that the SDK was dismissed. This to support any kind of navigation that the consumer could be implementing to show our SDK.
[IPC-776]
- A new `delegate` method was added so the consumer app can be listening to it to know if the SDK was dismissed. 
- At the example app a new option `Use alternative navigation` was added to `settings` menu to enable the alternative navigation to validate the new delegate. 
[IPC-776]: https://ginis.atlassian.net/browse/IPC-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ipc 776 sdk dismissal and duplicated bank list

---

.github/workflows/health-api-library.build.docs.yml
.github/workflows/health-api-library.check.yml
.github/workflows/health-api-library.publish.docs.yml
.github/workflows/health-api-library.release.yml
.github/workflows/health-sdk.build.docs.yml
.github/workflows/health-sdk.build.xcframeworks.xcode16.yml
.github/workflows/health-sdk.build.xcframeworks.yml
.github/workflows/health-sdk.check.yml
.github/workflows/health-sdk.publish.docs.yml
.github/workflows/health-sdk.publish.example.apps.firebase.yml
.github/workflows/health-sdk.release.yml
.github/workflows/internal-payment-sdk.check.yml
.github/workflows/internal-payment-sdk.release.yml
.github/workflows/merchant-sdk.build.docs.yml
.github/workflows/merchant-sdk.check.yml
.github/workflows/merchant-sdk.publish.docs.yml
.github/workflows/merchant-sdk.publish.example.apps.firebase.yml
.github/workflows/merchant-sdk.release.yml
.github/workflows/utilites.check.yml
.github/workflows/utilites.release.yml
HealthSDK/GiniHealthSDK/.jazzy.yaml
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample.xcodeproj/project.pbxproj
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/AppDelegate.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/GoogleService-Info.plist
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample/Info.plist
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExampleTests/AlternativeNavigationTests.swift
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExampleTests/GiniSetupHelper.swift
HealthSDK/GiniHealthSDKExample/GoogleService-Info.plist
MerchantSDK/GiniMerchantSDK/.jazzy.yaml

This PR includes:
- The missing unit tests for `GiniHealthSDKExample` target for the new functionality
- Enabling Firebase for `GiniHealthSDKExample`
[IPC-783]
- The `AlternativeNavigationTests` were added to test the different scenarios of listening to SDK dismissal.
- The SPM for Firebase was added as dependency to see `Crashlytics` and `Performance`
[IPC-783]: https://ginis.atlassian.net/browse/IPC-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ipc 783 release unit tests

---

CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera/CameraViewController.swift

[PP-1403](https://ginis.atlassian.net/browse/PP-1403)
This PR fixes the camera title display issue in landscape orientation on iPhones and is migrating localized strings to a private struct and updates the title configuration logic. The main goal is to ensure the title screen displays correctly in landscape mode on iPhones within the camera screen.
Simplified and reorganized the configureTitle() method with clearer logic for different device orientations and configurations
Migrated hardcoded localized string calls to a centralized private Strings struct for better maintainability
Added title reconfiguration during orientation changes to ensure proper display in landscape mode
[PP-1403]: https://ginis.atlassian.net/browse/PP-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

fix(GiniCaptureSDK):  Fix title screen in landscape on iPhones in CameraScreen

---

BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/Onboarding/DigitalInvoiceOnboardingViewController.swift

[PP-1544](https://ginis.atlassian.net/browse/PP-1544)
This PR fixes VoiceOver accessibility behavior on iPad when switching to landscape orientation by updating the accessibility elements logic to handle iPhone and iPad devices differently.
Updated accessibility element selection logic to use pattern matching with device type and orientation
Fixed iPad landscape orientation to use the same accessibility elements as portrait mode
Replaced if-else conditional with a switch statement for clearer device-specific logic
Tested on:
IPad Air(5th generation 17.5)
iPad Pro(11 inch 15.5)
iPad(A16 18.3)
iPad mini(6th gen 18.0)
[PP-1544]: https://ginis.atlassian.net/browse/PP-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pp 1544 in i pad devices voice over ra onboarding screen changing the orientation is not reading the elements

---

.github/workflows/bank-sdk.publish.example.app.firebase.yml
BankSDK/GiniBankSDKExample/GiniBankSDKExample.xcodeproj/project.pbxproj
BankSDK/GiniBankSDKExample/GiniBankSDKExample/AppDelegate.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/DemoViewController.swift
BankSDK/GiniBankSDKExample/GoogleService-Info.plist
GiniMobile.xcworkspace/xcshareddata/swiftpm/Package.resolved
HealthSDK/GiniHealthSDKExample/GiniHealthSDKExample.xcodeproj/project.pbxproj

This pull request introduces FirebaseCrashlytics and FirebasePerformance frameworks to the GiniBankSDKExample app.
To achieve this, I followed all the steps [described](https://firebase.google.com/docs/crashlytics/get-started?platform=ios) here.
**Important** to know that we need to use Firebase version 11.11.0 and not other version above this one because of the deprecation of the Xcode 15 version.
Check the release notes for[ Version 11.12.0](https://firebase.google.com/support/release-notes/ios#version_11120_-_april_21_2025), where they mentioned they dropped support for Xcode15.
For us is important because GitHub Actions are still configured to run on Xcode 15.
If you want to test, please follow the steps described [here](https://firebase.google.com/docs/crashlytics/get-started?platform …

Enable crashlytics bank sdk example app

---

.github/workflows/bank-api-library.check.yml
.github/workflows/bank-sdk.check.yml
.github/workflows/capture-sdk.check.yml
.github/workflows/health-api-library.check.yml
.github/workflows/health-sdk.check.yml
.github/workflows/internal-payment-sdk.check.yml
.github/workflows/merchant-sdk.check.yml
.github/workflows/utilites.check.yml
BankSDK/GiniBankSDK/.swiftpm/xcode/xcshareddata/xcschemes/GiniBankSDK.xcscheme
CaptureSDK/GiniCaptureSDK/.swiftpm/xcode/xcshareddata/xcschemes/GiniCaptureSDK.xcscheme
CaptureSDK/GiniCaptureSDKPinning/.swiftpm/xcode/xcshareddata/xcschemes/GiniCaptureSDKPinning.xcscheme
GiniComponents/GiniUtilites/.swiftpm/xcode/xcshareddata/xcschemes/GiniUtilites.xcscheme
HealthSDK/GiniHealthSDK/.swiftpm/xcode/xcshareddata/xcschemes/GiniHealthSDK.xcscheme
fastlane/Fastfile
fastlane/README.md

[PP-1820](https://ginis.atlassian.net/browse/PP-1820)
This PR adds a new Fastlane lane for running unit tests with configurable parameters. The lane provides a standardized way to execute unit tests for specific targets with custom destinations and client secrets.
Key changes:
- Added run_unit_tests lane with support for target, destination, clientId, and clientSecret parameters
- Updated Xcode scheme to include test target configuration
- Generated corresponding documentation for the new lane
Local Usage:
`bundle exec fastlane run_unit_tests target:"GiniBankAPILibrary" destination:"platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" clientId:"<secretid>"  clientSecret:"<secret>"`
[PP-1820]: https://ginis.atlassian.net/browse/PP-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

Unit tests fastlane lane

---

BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Configuration/ClientConfiguration.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/ClientConfigurationTests.swift
BankAPILibrary/GiniBankAPILibrary/Tests/GiniBankAPILibraryTests/Resources/clientConfiguration.json
BankSDK/GiniBankSDK/Tests/GiniBankSDKTests/NetworkingScreenApiCoordinatorTests.swift
BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController+SwitchOptionModel.swift
BankSDK/GiniBankSDKExample/Tests/IntegrationTests/ClientConfiguration/ClientConfigurationTests.swift

[PP-1909](https://ginis.atlassian.net/browse/PP-1909)
This PR implements client configuration properties for payment due date default values by adding two new threshold fields to the ClientConfiguration struct. The changes support configuring the minimum payment amount and the number of days before due date for triggering the warning.
- Added `paymentDueDateAmountThreshold` and `paymentDueDateDaysThreshold` string properties to ClientConfiguration
- Updated all ClientConfiguration initializations across tests and example code to include the new threshold parameters
- Added comprehensive test coverage for the new threshold properties
[PP-1909]: https://ginis.atlassian.net/browse/PP-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pp 1909 implement the client configuration properties for the default values
